//
// Generated by IntelliAsnCC ASN.1 compiler (C, C++, Java).
//
// Do not edit!
//
//
//
// (C) 2000, 2001 IntelliNet Technologies Inc. All Rights Reserved.
//
//


#include <map_v1_deregister_mobile_subscriber_arg.h>


using namespace its;
using namespace map_v1;


// Type DeregisterMobileSubscriberArg is a reference => no code generated.




