//
// Generated by IntelliAsnCC ASN.1 compiler (C, C++, Java).
//
// Do not edit!
//
//
//
// (C) 2000, 2001 IntelliNet Technologies Inc. All Rights Reserved.
//
//


#include <map_v9_ccbs_request_state.h>

#include <AsnDescEnumerated.h>


using namespace its;
using namespace map_v9;



AsnDescObject* CCBS_RequestState::GetStaticDescription()
{
    static volatile bool initialized = false;
    static AsnDescObject* result = NULL;
    static AsnDescEnumerated staticDesc;

    if (initialized)
    {
        return result;
    }

    Asn::Lock();

    if (initialized)
    {
        Asn::Unlock();
        return result;
    }
    else
    {
        if (CheckLicense(ITS_LIC_CAP_GSMMAP) != ITS_TRUE)
        {
            Asn::Unlock();
            exit(0);
        }

        staticDesc.SetCloneForFactory(new CCBS_RequestState(&staticDesc));
        staticDesc.TagAddLevel(new Tag(Tag::ASN_CLASS_UNIVERSAL, Tag::ASN_PRIMITIVE, 10));
        staticDesc._valueSet.insert(0);
        staticDesc._valueSet.insert(1);
        staticDesc._valueSet.insert(2);
        staticDesc._valueSet.insert(3);
        staticDesc._valueSet.insert(4);
        staticDesc._valueSet.insert(5);
        staticDesc._valueSet.insert(6);
        static AsnDescEnumerated::NamedNumber namedNumberList[] = {{"request", 0}, {"recall", 1}, {"active", 2}, {"completed", 3}, {"suspended", 4}, {"frozen", 5}, {"deleted", 6}, {NULL, 0}};
        staticDesc.SetNamedNumberList(namedNumberList);
        static AsnDescEnumerated::NamedNumber namedNumberExtList[] = {{NULL, 0}};
        staticDesc.SetNamedNumberExtList(namedNumberExtList);
        staticDesc.SetTypeName("CCBS-RequestState");
        result = &staticDesc;
        initialized = true;
        Asn::Unlock();
        return result;
    }
}

long CCBS_RequestState::Get(const std::string& valueName) const
{
    if (valueName == "request")
    {
        return 0;
    }
    else if (valueName == "recall")
    {
        return 1;
    }
    else if (valueName == "active")
    {
        return 2;
    }
    else if (valueName == "completed")
    {
        return 3;
    }
    else if (valueName == "suspended")
    {
        return 4;
    }
    else if (valueName == "frozen")
    {
        return 5;
    }
    else if (valueName == "deleted")
    {
        return 6;
    }
    else
    {
        bool invalid_value_name = false;
        ITS_ASSERT(invalid_value_name);

        return 0;
    }
}

std::string CCBS_RequestState::Get(long value) const
{
    if (value == 0)
    {
        return "request";
    }
    else if (value == 1)
    {
        return "recall";
    }
    else if (value == 2)
    {
        return "active";
    }
    else if (value == 3)
    {
        return "completed";
    }
    else if (value == 4)
    {
        return "suspended";
    }
    else if (value == 5)
    {
        return "frozen";
    }
    else if (value == 6)
    {
        return "deleted";
    }
    else
    {
        bool invalid_value = false;
        ITS_ASSERT(invalid_value);

        return "";
    }
}

std::string CCBS_RequestState::GetExt(long value) const
{
    return "";
}





