//
// Generated by IntelliAsnCC ASN.1 compiler (C, C++, Java).
//
// Do not edit!
//
//
//
// (C) 2000, 2001 IntelliNet Technologies Inc. All Rights Reserved.
//
//


#include <map_v13_roaming_not_allowed_cause.h>

#include <AsnDescEnumerated.h>


using namespace its;
using namespace map_v13;



AsnDescObject* RoamingNotAllowedCause::GetStaticDescription()
{
    static volatile bool initialized = false;
    static AsnDescObject* result = NULL;
    static AsnDescEnumerated staticDesc;

    if (initialized)
    {
        return result;
    }

    Asn::Lock();

    if (initialized)
    {
        Asn::Unlock();
        return result;
    }
    else
    {
        staticDesc.SetCloneForFactory(new RoamingNotAllowedCause(&staticDesc));
        staticDesc.TagAddLevel(new Tag(Tag::ASN_CLASS_UNIVERSAL, Tag::ASN_PRIMITIVE, 10));
        staticDesc._valueSet.insert(0);
        staticDesc._valueSet.insert(3);
        static AsnDescEnumerated::NamedNumber namedNumberList[] = {{"plmnRoamingNotAllowed", 0}, {"operatorDeterminedBarring", 3}, {NULL, 0}};
        staticDesc.SetNamedNumberList(namedNumberList);
        static AsnDescEnumerated::NamedNumber namedNumberExtList[] = {{NULL, 0}};
        staticDesc.SetNamedNumberExtList(namedNumberExtList);
        staticDesc.SetTypeName("RoamingNotAllowedCause");
        result = &staticDesc;
        initialized = true;
        Asn::Unlock();
        return result;
    }
}

long RoamingNotAllowedCause::Get(const std::string& valueName) const
{
    if (valueName == "plmnRoamingNotAllowed")
    {
        return 0;
    }
    else if (valueName == "operatorDeterminedBarring")
    {
        return 3;
    }
    else
    {
        bool invalid_value_name = false;
        ITS_ASSERT(invalid_value_name);

        return 0;
    }
}

std::string RoamingNotAllowedCause::Get(long value) const
{
    if (value == 0)
    {
        return "plmnRoamingNotAllowed";
    }
    else if (value == 3)
    {
        return "operatorDeterminedBarring";
    }
    else
    {
        bool invalid_value = false;
        ITS_ASSERT(invalid_value);

        return "";
    }
}

std::string RoamingNotAllowedCause::GetExt(long value) const
{
    return "";
}





