include ${EACC_ROOT}/Makefile.inc

CXXFLAGS += -I${EACC_ROOT}/blocks/include -I${EACC_ROOT}/mess/include -I${EACC_ROOT}/cmapi/idl/

HA_COMPONENT_AR := libHAComponent.a
HA_COMPONENT_OFILES := HAMeSSComponent.o \


TARGETS_AR := HA_COMPONENT

include ${EACC_ROOT}/Makefile.rules

