export IWF_ROOT=/opt/diametriq/iwf
export ROOT=$IWF_ROOT
export ISS7_CONFIG_DIR=$IWF_ROOT/config/
export IWF_CONFIG_FILE=$IWF_ROOT/bin/iwf.json
export WEBGUI_ROOT=$IWF_ROOT/WebGUI
export SSG_LOG_DIR=/var/log/iwf/
export ROSIM_IWF_CONFIG_FILE=$IWF_ROOT/test/ro_r10_sim/bin/ro_r10_tools.json
export RO_TRANSATEL_IWF_CONFIG_FILE=$IWF_ROOT/test/ro_r10_transatel/bin/ro_r10_tools.json
export CAPSIM_IWF_CONFIG_FILE=$IWF_ROOT/test/capsim/bin/cap_tools.json
export MAP_IWF_CONFIG_FILE=$IWF_ROOT/test/map/bin/map_tools.json
export CAP_ROOt=$IWF_ROOT/test/map/bin/
export MAPSIM_IWF_CONFIG_FILE=$IWF_ROOT/test/capsim/bin/map_tools.json
export S6A_IWF_CONFIG_FILE=$IWF_ROOT/test/s6a_r10/bin/s6a_tools.json
export RO_IWF_CONFIG_FILE=$IWF_ROOT/test/ro_r10/bin/ro_r10_tools.json
export CAP_IWF_CONFIG_FILE=$IWF_ROOT/test/map/bin/cap_tools.json
export CAP_IWFPERF_CONFIG_FILE=$IWF_ROOT/test/PerfSim/bin/cap_tools.json
export RO_ROOT=$IWF_ROOT/test/ro_r10/bin/
export LD_LIBRARY_PATH=$IWF_ROOT/lib:$LD_LIBRARY_PATH
export DRE_MYSQL_SERVER_CONFDIR=$IWF_ROOT/config/mysql
export DRE_LOG_DIR=/var/log/dre
export DRE_STATS_DIR=/var/log/dre/stats
#export SSG_LOG_DIR=/var/log/iwf
export DRE_SESS_TRACE_PATH=$DRE_LOG_DIR/trace/
export DRE_SESS_TRACE_CONFIG=$IWF_ROOT/config/trace.json
export PATH=$IWF_ROOT/bin:$PATH
export DRE_STATUS_FILE=$IWF_ROOT/config/iwfStatusFile
export JRE_HOME=`rpm -ql jre | grep "/bin/java" | sed 's/bin\/java//' | awk 'NR<2{ print $1 }'`

