#!/bin/bash
#
# chkconfig: 2345 11 89
# description: pre-dre
# this script is used to perform any operations that are required prior
# to starting the dre service
PRODUCT=iwf

# Get function from functions library
. /etc/init.d/functions

# Start the service pre-dre
start() {
        echo "yes" > /etc/.$PRODUCT/boot
}
stop()
{
  echo "stop"
}

### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status pre-dre
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0

