###############################################################################
#                                                                              #
#      Copyright 2000 IntelliNet Technologies, Inc. All Rights Reserved.       #
#              Manufactured in the United States of America.                   #
#        1990 W. New Haven Ste. 312, Melbourne, Florida, 32904 U.S.A.          #
#                                                                              #
#     This product and related documentation is protected by copyright and     #
#     distributed under licenses restricting its use, copying, distribution    #
#     and decompilation.  No part of this product or related documentation     #
#     may be reproduced in any form by any means without prior written         #
#     authorization of IntelliNet Technologies and its licensors, if any.      #
#                                                                              #
#     RESTRICTED RIGHTS LEGEND:  Use, duplication, or disclosure by the        #
#     government is subject to restrictions as set forth in subparagraph       #
#     (c)(1)(ii) of the Rights in Technical Data and Computer Software         #
#     clause at DFARS 252.227-7013 and FAR 52.227-19.                          #
#                                                                              #
################################################################################
#                                                                              #
# CONTRACT: Internal                                                           #
#                                                                              #
################################################################################
#
#  ID: $Id: Makefile.ltest,v 9.1 2005/03/23 12:52:40 cvsadmin Exp $
#
################################################################################

#
# get the vars
#
include $(ITS_ROOT)/config.vars

OBJS=ltest.o other.o

LIBS=-L../../common/lib -L../lib -lANSI-TCAPD -lSUPPORTD -lCORED \
	-lSUPPORTD -lCORED

CXXFLAGS := $(CXXFLAGS) -I$(ITS_ROOT)/common/include -I../include \
	   -I../../SCCP/include -I../../MTP3/include -I../../MTP2/include -DANSI

ltest$(DBGSUFFIX): $(OBJS)
	$(CXX) -o ltest $(OBJS) $(LIBS) $(SYSLIBS) $(THREADLIBS) $(SOCKLIBS)

clean:
	$(RM) $(OBJS)
            
#
# get the rules
#
include $(ITS_ROOT)/config.rules


