/**
 *
 *   @file  CMApiCompCmn.h
 *
 *  @brief  Common Includes
 *
 *
 **/
   

enum CompoReqIDs { GET_PEERGROUP = 0, ADD_PEERGROUP, MOD_PEERGROUP, DEL_PEERGROUP, GET_PEERCONFIG, 
    ADD_PEERCONFIG, MOD_PEERCONFIG, DEL_PEERCONFIG, ADD_LBALGO, MOD_LBALGO, GET_LBALGO, DEL_LBALGO,
    INVALID_REQID 
};

enum CompoLibRetCodes { CMAPI_SUCCESS = 0, CMAPI_ERROR, CMAPI_INVALIDPARAMS, CMAPI_MESSERROR, CMAPI_SRVERROR };
