include ../Makefile.inc

CXXFLAGS += -I../blocks/include

MESS_AR := libmess.a
MESS_OFILES := TopSrv.o MeSSage.o Transceiver.o MeSS.o MeSSComponent.o \


TARGETS_AR := MESS

include ../Makefile.rules

