//
// Generated by IntelliAsnCC ASN.1 compiler (C, C++, Java).
//
// Do not edit!
//
//
//
// (C) 2000, 2001 IntelliNet Technologies Inc. All Rights Reserved.
//
//


#if !defined(_MAP_V1_L_MS_ID_H_)
#define _MAP_V1_L_MS_ID_H_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

#include <Asn.h>
#include <AsnObject.h>
#include <AsnDescObject.h>
#include <AsnError.h>

#include <AsnOctetString.h>



namespace map_v1 {



class LMsId : public its::AsnOctetString
{
public:

    LMsId() : its::AsnOctetString(false)
    {
        Initialize();
    }

    LMsId(const std::vector<byte>& array) : its::AsnOctetString(array, false)
    {
        Initialize();
    }

    LMsId(its::Octets& octets) : its::AsnOctetString(false)
    {
        Initialize();
        Decode(octets);
    }

    LMsId(const LMsId& rhs) : its::AsnOctetString(rhs)
    {
        // Nothing to do.
    }

    LMsId(its::AsnDescObject* description) : its::AsnOctetString(description)
    {
        // Nothing to do.
    }

    LMsId(its::AsnDescObject* description, const std::vector<byte>& array) : its::AsnOctetString(description, array)
    {
        // Nothing to do.
    }

protected:

    void Initialize()
    {
        _description = GetStaticDescription();
    }

public:

    static its::AsnDescObject* GetStaticDescription();

public:

    virtual ~LMsId()
    {
        // Nothing to do.
    }

    virtual its::AsnObject* Clone() const
    {
        return new LMsId(*this);
    }

    virtual std::string GetName() const
    { return "LMsId"; }

};



} // namespace.

#endif    // !defined(_MAP_V1_L_MS_ID_H_)

