//
// Generated by IntelliAsnCC ASN.1 compiler (C, C++, Java).
//
// Do not edit!
//
//
//
// (C) 2000, 2001 IntelliNet Technologies Inc. All Rights Reserved.
//
//


#if !defined(_MAP_V9_HOP_COUNTER_H_)
#define _MAP_V9_HOP_COUNTER_H_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

#include <Asn.h>
#include <AsnObject.h>
#include <AsnDescObject.h>
#include <AsnError.h>

#include <AsnInteger.h>



namespace map_v9 {



class HopCounter : public its::AsnInteger
{
public:

    HopCounter() : its::AsnInteger(false)
    {
        Initialize();
    }

    HopCounter(long value) : its::AsnInteger(value, false)
    {
        Initialize();
    }

    HopCounter(its::Octets& octets) : its::AsnInteger(false)
    {
        Initialize();
        Decode(octets);
    }

    HopCounter(const HopCounter& rhs) : its::AsnInteger(rhs)
    {
        // Nothing to do.
    }

    HopCounter(its::AsnDescObject* description) : its::AsnInteger(description)
    {
        // Nothing to do.
    }

    HopCounter(its::AsnDescObject* description, long value) : its::AsnInteger(description, value)
    {
        // Nothing to do.
    }

protected:

    void Initialize()
    {
        _description = GetStaticDescription();
    }

public:

    static its::AsnDescObject* GetStaticDescription();

public:

    virtual ~HopCounter()
    {
        // Nothing to do.
    }

    virtual its::AsnObject* Clone() const
    {
        return new HopCounter(*this);
    }

    virtual std::string GetName() const
    { return "HopCounter"; }

};



} // namespace.

#endif    // !defined(_MAP_V9_HOP_COUNTER_H_)

