//
// Generated by IntelliAsnCC ASN.1 compiler (C, C++, Java).
//
// Do not edit!
//
//
//
// (C) 2000, 2001 IntelliNet Technologies Inc. All Rights Reserved.
//
//


#if !defined(_MAP_V1_SS_DATA_H_)
#define _MAP_V1_SS_DATA_H_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

#include <Asn.h>
#include <AsnObject.h>
#include <AsnDescObject.h>
#include <AsnError.h>

#include <AsnSequence.h>
#include <AsnOctetString.h>
#include <AsnChoice.h>

#include <map_v1_ss_code.h>
#include <map_v1_ss_status.h>
#include <map_v1_ss_subscription_option.h>



namespace map_v1 {



class SS_Data : public its::AsnSequence
{
public:


////////// Begin Nested Class(es) //////////


        typedef map_v1::SS_Code SS_Code;


        typedef map_v1::SS_Status SS_Status;


        typedef map_v1::SS_SubscriptionOption SS_SubscriptionOption;


////////// End Nested Class(es) //////////

    SS_Data() : its::AsnSequence(3, false)
    {
        Initialize();
    }

    SS_Data(its::Octets& octets) : its::AsnSequence(3, false)
    {
        Initialize();
        Decode(octets);
    }

    SS_Data(const SS_Data& rhs) : its::AsnSequence(rhs)
    {
        // Nothing to do.
    }

    SS_Data(its::AsnDescObject* description) : its::AsnSequence(3, description)
    {
        // Nothing to do.
    }

protected:

    void Initialize()
    {
        _description = GetStaticDescription();
    }

public:

    static its::AsnDescObject* GetStaticDescription();

    static its::AsnDescObject* GetSs_CodeStaticDescription();
    static its::AsnDescObject* GetSs_StatusStaticDescription();
    static its::AsnDescObject* GetSs_SubscriptionStaticDescription();

public:

    virtual ~SS_Data()
    {
        // Nothing to do.
    }

    virtual its::AsnObject* Clone() const
    {
        return new SS_Data(*this);
    }

    virtual std::string GetName() const
    { return "SS_Data"; }

    void SetSs_Code(SS_Code* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetSs_CodeStaticDescription());
        AddElement(0, element);
    }

    void SetSs_Code(const SS_Code& element)
    {
        its::AsnObject& asnObject = const_cast<SS_Code&>(element);
        asnObject.SetDescription(GetSs_CodeStaticDescription());
        AddElement(0, element);
    }

    const SS_Code& GetSs_Code() const
    {
        return static_cast<const SS_Code&> (ElementAt(0));
    }

    void SetSs_Status(SS_Status* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetSs_StatusStaticDescription());
        AddElement(1, element);
    }

    void SetSs_Status(const SS_Status& element)
    {
        its::AsnObject& asnObject = const_cast<SS_Status&>(element);
        asnObject.SetDescription(GetSs_StatusStaticDescription());
        AddElement(1, element);
    }

    bool OptionSs_Status() const
    {
        return Contains(1);
    }

    const SS_Status& GetSs_Status() const
    {
        ITS_REQUIRE(OptionSs_Status());
        return static_cast<const SS_Status&> (ElementAt(1));
    }

    void SetSs_Subscription(SS_SubscriptionOption* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetSs_SubscriptionStaticDescription());
        AddElement(2, element);
    }

    void SetSs_Subscription(const SS_SubscriptionOption& element)
    {
        its::AsnObject& asnObject = const_cast<SS_SubscriptionOption&>(element);
        asnObject.SetDescription(GetSs_SubscriptionStaticDescription());
        AddElement(2, element);
    }

    bool OptionSs_Subscription() const
    {
        return Contains(2);
    }

    const SS_SubscriptionOption& GetSs_Subscription() const
    {
        ITS_REQUIRE(OptionSs_Subscription());
        return static_cast<const SS_SubscriptionOption&> (ElementAt(2));
    }

};



} // namespace.

#endif    // !defined(_MAP_V1_SS_DATA_H_)

