//
// Generated by IntelliAsnCC ASN.1 compiler (C, C++, Java).
//
// Do not edit!
//
//
//
// (C) 2000, 2001 IntelliNet Technologies Inc. All Rights Reserved.
//
//


#if !defined(_MAP_V13_ADDITIONAL_SUBSCRIPTIONS_H_)
#define _MAP_V13_ADDITIONAL_SUBSCRIPTIONS_H_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

#include <Asn.h>
#include <AsnObject.h>
#include <AsnDescObject.h>
#include <AsnError.h>

#include <AsnBitString.h>



namespace map_v13 {



class AdditionalSubscriptions : public its::AsnBitString
{
public:

    AdditionalSubscriptions() : its::AsnBitString(false)
    {
        Initialize();
    }

    AdditionalSubscriptions(const std::vector<bool>& array) : its::AsnBitString(array, false)
    {
        Initialize();
    }

    AdditionalSubscriptions(its::Octets& octets) : its::AsnBitString(false)
    {
        Initialize();
        Decode(octets);
    }

    AdditionalSubscriptions(const AdditionalSubscriptions& rhs) : its::AsnBitString(rhs)
    {
        // Nothing to do.
    }

    AdditionalSubscriptions(its::AsnDescObject* description) : its::AsnBitString(description)
    {
        // Nothing to do.
    }

    AdditionalSubscriptions(its::AsnDescObject* description, const std::vector<bool>& array) : its::AsnBitString(description, array)
    {
        // Nothing to do.
    }

protected:

    void Initialize()
    {
        _description = GetStaticDescription();
    }

public:

    static its::AsnDescObject* GetStaticDescription();

public:

    virtual ~AdditionalSubscriptions()
    {
        // Nothing to do.
    }

    virtual its::AsnObject* Clone() const
    {
        return new AdditionalSubscriptions(*this);
    }

    virtual std::string GetName() const
    { return "AdditionalSubscriptions"; }

    void SetEmergencyReset()
    { Set(2); }

    void ResetEmergencyReset()
    { Reset(2); }

    bool IsEmergencyResetSet() const
    { return IsSet(2); }

    bool IsEmergencyResetDefined() const
    { return 2 < GetSize(); }

    void SetEmergencyUplinkRequest()
    { Set(1); }

    void ResetEmergencyUplinkRequest()
    { Reset(1); }

    bool IsEmergencyUplinkRequestSet() const
    { return IsSet(1); }

    bool IsEmergencyUplinkRequestDefined() const
    { return 1 < GetSize(); }

    void SetPrivilegedUplinkRequest()
    { Set(0); }

    void ResetPrivilegedUplinkRequest()
    { Reset(0); }

    bool IsPrivilegedUplinkRequestSet() const
    { return IsSet(0); }

    bool IsPrivilegedUplinkRequestDefined() const
    { return 0 < GetSize(); }

};



} // namespace.

#endif    // !defined(_MAP_V13_ADDITIONAL_SUBSCRIPTIONS_H_)

