//
// Generated by IntelliAsnCC ASN.1 compiler (C, C++, Java).
//
// Do not edit!
//
//
//
// (C) 2000, 2001 IntelliNet Technologies Inc. All Rights Reserved.
//
//


#if !defined(_MAP_V3_REPORT_SM_DELIVERY_STATUS_ARG_H_)
#define _MAP_V3_REPORT_SM_DELIVERY_STATUS_ARG_H_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

#include <Asn.h>
#include <AsnObject.h>
#include <AsnDescObject.h>
#include <AsnError.h>

#include <AsnSequence.h>
#include <AsnOctetString.h>
#include <AsnEnumerated.h>
#include <AsnInteger.h>

#include <map_v3_isdn_address_string.h>
#include <map_v3_address_string.h>
#include <map_v3_sm_delivery_outcome.h>
#include <map_v3_absent_subscriber_diagnostic_sm.h>
#include <map_v3_extension_container.h>



namespace map_v3 {



class ReportSM_DeliveryStatusArg : public its::AsnSequence
{
public:


////////// Begin Nested Class(es) //////////


        typedef map_v3::ISDN_AddressString ISDN_AddressString;


        typedef map_v3::AddressString AddressString;


        typedef map_v3::SM_DeliveryOutcome SM_DeliveryOutcome;


        typedef map_v3::AbsentSubscriberDiagnosticSM AbsentSubscriberDiagnosticSM;


        typedef map_v3::ExtensionContainer ExtensionContainer;


////////// End Nested Class(es) //////////

    ReportSM_DeliveryStatusArg() : its::AsnSequence(5, false)
    {
        Initialize();
    }

    ReportSM_DeliveryStatusArg(its::Octets& octets) : its::AsnSequence(5, false)
    {
        Initialize();
        Decode(octets);
    }

    ReportSM_DeliveryStatusArg(const ReportSM_DeliveryStatusArg& rhs) : its::AsnSequence(rhs)
    {
        // Nothing to do.
    }

    ReportSM_DeliveryStatusArg(its::AsnDescObject* description) : its::AsnSequence(5, description)
    {
        // Nothing to do.
    }

protected:

    void Initialize()
    {
        _description = GetStaticDescription();
    }

public:

    static its::AsnDescObject* GetStaticDescription();

    static its::AsnDescObject* GetMsisdnStaticDescription();
    static its::AsnDescObject* GetServiceCentreAddressStaticDescription();
    static its::AsnDescObject* GetSm_DeliveryOutcomeStaticDescription();
    static its::AsnDescObject* GetAbsentSubscriberDiagnosticSMStaticDescription();
    static its::AsnDescObject* GetExtensionContainerStaticDescription();

public:

    virtual ~ReportSM_DeliveryStatusArg()
    {
        // Nothing to do.
    }

    virtual its::AsnObject* Clone() const
    {
        return new ReportSM_DeliveryStatusArg(*this);
    }

    virtual std::string GetName() const
    { return "ReportSM_DeliveryStatusArg"; }

    void SetMsisdn(ISDN_AddressString* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetMsisdnStaticDescription());
        AddElement(0, element);
    }

    void SetMsisdn(const ISDN_AddressString& element)
    {
        its::AsnObject& asnObject = const_cast<ISDN_AddressString&>(element);
        asnObject.SetDescription(GetMsisdnStaticDescription());
        AddElement(0, element);
    }

    const ISDN_AddressString& GetMsisdn() const
    {
        return static_cast<const ISDN_AddressString&> (ElementAt(0));
    }

    void SetServiceCentreAddress(AddressString* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetServiceCentreAddressStaticDescription());
        AddElement(1, element);
    }

    void SetServiceCentreAddress(const AddressString& element)
    {
        its::AsnObject& asnObject = const_cast<AddressString&>(element);
        asnObject.SetDescription(GetServiceCentreAddressStaticDescription());
        AddElement(1, element);
    }

    const AddressString& GetServiceCentreAddress() const
    {
        return static_cast<const AddressString&> (ElementAt(1));
    }

    void SetSm_DeliveryOutcome(SM_DeliveryOutcome* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetSm_DeliveryOutcomeStaticDescription());
        AddElement(2, element);
    }

    void SetSm_DeliveryOutcome(const SM_DeliveryOutcome& element)
    {
        its::AsnObject& asnObject = const_cast<SM_DeliveryOutcome&>(element);
        asnObject.SetDescription(GetSm_DeliveryOutcomeStaticDescription());
        AddElement(2, element);
    }

    const SM_DeliveryOutcome& GetSm_DeliveryOutcome() const
    {
        return static_cast<const SM_DeliveryOutcome&> (ElementAt(2));
    }

    void SetAbsentSubscriberDiagnosticSM(AbsentSubscriberDiagnosticSM* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetAbsentSubscriberDiagnosticSMStaticDescription());
        AddElement(3, element);
    }

    void SetAbsentSubscriberDiagnosticSM(const AbsentSubscriberDiagnosticSM& element)
    {
        its::AsnObject& asnObject = const_cast<AbsentSubscriberDiagnosticSM&>(element);
        asnObject.SetDescription(GetAbsentSubscriberDiagnosticSMStaticDescription());
        AddElement(3, element);
    }

    bool OptionAbsentSubscriberDiagnosticSM() const
    {
        return Contains(3);
    }

    const AbsentSubscriberDiagnosticSM& GetAbsentSubscriberDiagnosticSM() const
    {
        ITS_REQUIRE(OptionAbsentSubscriberDiagnosticSM());
        return static_cast<const AbsentSubscriberDiagnosticSM&> (ElementAt(3));
    }

    void SetExtensionContainer(ExtensionContainer* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetExtensionContainerStaticDescription());
        AddElement(4, element);
    }

    void SetExtensionContainer(const ExtensionContainer& element)
    {
        its::AsnObject& asnObject = const_cast<ExtensionContainer&>(element);
        asnObject.SetDescription(GetExtensionContainerStaticDescription());
        AddElement(4, element);
    }

    bool OptionExtensionContainer() const
    {
        return Contains(4);
    }

    const ExtensionContainer& GetExtensionContainer() const
    {
        ITS_REQUIRE(OptionExtensionContainer());
        return static_cast<const ExtensionContainer&> (ElementAt(4));
    }

};



} // namespace.

#endif    // !defined(_MAP_V3_REPORT_SM_DELIVERY_STATUS_ARG_H_)

