//
// Generated by IntelliAsnCC ASN.1 compiler (C, C++, Java).
//
// Do not edit!
//
//
//
// (C) 2000, 2001 IntelliNet Technologies Inc. All Rights Reserved.
//
//


#if !defined(_MAP_V9_DESTINATION_NUMBER_LIST_H_)
#define _MAP_V9_DESTINATION_NUMBER_LIST_H_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

#include <Asn.h>
#include <AsnObject.h>
#include <AsnDescObject.h>
#include <AsnError.h>

#include <AsnSequenceOf.h>
#include <AsnOctetString.h>

#include <map_v9_isdn_address_string.h>



namespace map_v9 {



class DestinationNumberList : public its::AsnSequenceOf
{
public:


////////// Begin Nested Class //////////


        typedef map_v9::ISDN_AddressString ISDN_AddressString;


////////// End Nested Class //////////

    DestinationNumberList() : its::AsnSequenceOf(false)
    {
        Initialize();
    }

    DestinationNumberList(its::Octets& octets) : its::AsnSequenceOf(false)
    {
        Initialize();
        Decode(octets);
    }

    DestinationNumberList(const DestinationNumberList& rhs) : its::AsnSequenceOf(rhs)
    {
        // Nothing to do.
    }

    DestinationNumberList(its::AsnDescObject* description) : its::AsnSequenceOf(description)
    {
        // Nothing to do.
    }

protected:

    void Initialize()
    {
        _description = GetStaticDescription();
    }

public:

    static its::AsnDescObject* GetStaticDescription();

    static its::AsnDescObject* GetISDN_AddressStringStaticDescription();

public:

    virtual ~DestinationNumberList()
    {
        // Nothing to do.
    }

    virtual its::AsnObject* Clone() const
    {
        return new DestinationNumberList(*this);
    }

    virtual std::string GetName() const
    { return "DestinationNumberList"; }

    void AddElement(ISDN_AddressString* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetISDN_AddressStringStaticDescription());
        AsnSequenceOf::AddElement(element);
    }

    void AddElement(const ISDN_AddressString& element)
    {
        its::AsnObject& asnObject = const_cast<ISDN_AddressString&>(element);
        asnObject.SetDescription(GetISDN_AddressStringStaticDescription());
        AsnSequenceOf::AddElement(element);
    }

    const ISDN_AddressString& ElementAt(int index) const
    {
        return static_cast<const ISDN_AddressString&> (AsnSequenceOf::ElementAt(index));
    }

};



} // namespace.

#endif    // !defined(_MAP_V9_DESTINATION_NUMBER_LIST_H_)

