//
// Generated by IntelliAsnCC ASN.1 compiler (C, C++, Java).
//
// Do not edit!
//
//
//
// (C) 2000, 2001 IntelliNet Technologies Inc. All Rights Reserved.
//
//


#if !defined(_MAP_V3_ODB_HPLMN_DATA_H_)
#define _MAP_V3_ODB_HPLMN_DATA_H_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

#include <Asn.h>
#include <AsnObject.h>
#include <AsnDescObject.h>
#include <AsnError.h>

#include <AsnBitString.h>



namespace map_v3 {



class ODB_HPLMN_Data : public its::AsnBitString
{
public:

    ODB_HPLMN_Data() : its::AsnBitString(false)
    {
        Initialize();
    }

    ODB_HPLMN_Data(const std::vector<bool>& array) : its::AsnBitString(array, false)
    {
        Initialize();
    }

    ODB_HPLMN_Data(its::Octets& octets) : its::AsnBitString(false)
    {
        Initialize();
        Decode(octets);
    }

    ODB_HPLMN_Data(const ODB_HPLMN_Data& rhs) : its::AsnBitString(rhs)
    {
        // Nothing to do.
    }

    ODB_HPLMN_Data(its::AsnDescObject* description) : its::AsnBitString(description)
    {
        // Nothing to do.
    }

    ODB_HPLMN_Data(its::AsnDescObject* description, const std::vector<bool>& array) : its::AsnBitString(description, array)
    {
        // Nothing to do.
    }

protected:

    void Initialize()
    {
        _description = GetStaticDescription();
    }

public:

    static its::AsnDescObject* GetStaticDescription();

public:

    virtual ~ODB_HPLMN_Data()
    {
        // Nothing to do.
    }

    virtual its::AsnObject* Clone() const
    {
        return new ODB_HPLMN_Data(*this);
    }

    virtual std::string GetName() const
    { return "ODB_HPLMN_Data"; }

    void SetPlmn_SpecificBarringType4()
    { Set(3); }

    void ResetPlmn_SpecificBarringType4()
    { Reset(3); }

    bool IsPlmn_SpecificBarringType4Set() const
    { return IsSet(3); }

    bool IsPlmn_SpecificBarringType4Defined() const
    { return 3 < GetSize(); }

    void SetPlmn_SpecificBarringType3()
    { Set(2); }

    void ResetPlmn_SpecificBarringType3()
    { Reset(2); }

    bool IsPlmn_SpecificBarringType3Set() const
    { return IsSet(2); }

    bool IsPlmn_SpecificBarringType3Defined() const
    { return 2 < GetSize(); }

    void SetPlmn_SpecificBarringType2()
    { Set(1); }

    void ResetPlmn_SpecificBarringType2()
    { Reset(1); }

    bool IsPlmn_SpecificBarringType2Set() const
    { return IsSet(1); }

    bool IsPlmn_SpecificBarringType2Defined() const
    { return 1 < GetSize(); }

    void SetPlmn_SpecificBarringType1()
    { Set(0); }

    void ResetPlmn_SpecificBarringType1()
    { Reset(0); }

    bool IsPlmn_SpecificBarringType1Set() const
    { return IsSet(0); }

    bool IsPlmn_SpecificBarringType1Defined() const
    { return 0 < GetSize(); }

};



} // namespace.

#endif    // !defined(_MAP_V3_ODB_HPLMN_DATA_H_)

