//
// Generated by IntelliAsnCC ASN.1 compiler (C, C++, Java).
//
// Do not edit!
//
//
//
// (C) 2000, 2001 IntelliNet Technologies Inc. All Rights Reserved.
//
//


#if !defined(_MAP_V13_ANY_TIME_SUBSCRIPTION_INTERROGATION_ARG_H_)
#define _MAP_V13_ANY_TIME_SUBSCRIPTION_INTERROGATION_ARG_H_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

#include <Asn.h>
#include <AsnObject.h>
#include <AsnDescObject.h>
#include <AsnError.h>

#include <AsnSequence.h>
#include <AsnNull.h>
#include <AsnChoice.h>
#include <AsnOctetString.h>

#include <map_v13_subscriber_identity.h>
#include <map_v13_requested_subscription_info.h>
#include <map_v13_isdn_address_string.h>
#include <map_v13_extension_container.h>



namespace map_v13 {



class AnyTimeSubscriptionInterrogationArg : public its::AsnSequence
{
public:


////////// Begin Nested Class(es) //////////



    class LongFTN_Supported : public its::AsnNull
    {
    public:

        LongFTN_Supported() : its::AsnNull(false)
        {
            Initialize();
        }

        LongFTN_Supported(its::Octets& octets) : its::AsnNull(false)
        {
            Initialize();
            Decode(octets);
        }

        LongFTN_Supported(const LongFTN_Supported& rhs) : its::AsnNull(rhs)
        {
            // Nothing to do.
        }

        LongFTN_Supported(its::AsnDescObject* description) : its::AsnNull(description)
        {
            // Nothing to do.
        }

    protected:

        void Initialize()
        {
            _description = GetStaticDescription();
        }

    public:

        static its::AsnDescObject* GetStaticDescription();

    public:

        virtual ~LongFTN_Supported()
        {
            // Nothing to do.
        }

        virtual its::AsnObject* Clone() const
        {
            return new LongFTN_Supported(*this);
        }

        virtual std::string GetName() const
        { return "LongFTN_Supported"; }

    };


        typedef map_v13::SubscriberIdentity SubscriberIdentity;


        typedef map_v13::RequestedSubscriptionInfo RequestedSubscriptionInfo;


        typedef map_v13::ISDN_AddressString ISDN_AddressString;


        typedef map_v13::ExtensionContainer ExtensionContainer;


////////// End Nested Class(es) //////////

    AnyTimeSubscriptionInterrogationArg() : its::AsnSequence(5, false)
    {
        Initialize();
    }

    AnyTimeSubscriptionInterrogationArg(its::Octets& octets) : its::AsnSequence(5, false)
    {
        Initialize();
        Decode(octets);
    }

    AnyTimeSubscriptionInterrogationArg(const AnyTimeSubscriptionInterrogationArg& rhs) : its::AsnSequence(rhs)
    {
        // Nothing to do.
    }

    AnyTimeSubscriptionInterrogationArg(its::AsnDescObject* description) : its::AsnSequence(5, description)
    {
        // Nothing to do.
    }

protected:

    void Initialize()
    {
        _description = GetStaticDescription();
    }

public:

    static its::AsnDescObject* GetStaticDescription();

    static its::AsnDescObject* GetSubscriberIdentityStaticDescription();
    static its::AsnDescObject* GetRequestedSubscriptionInfoStaticDescription();
    static its::AsnDescObject* GetGsmSCF_AddressStaticDescription();
    static its::AsnDescObject* GetExtensionContainerStaticDescription();
    static its::AsnDescObject* GetLongFTN_SupportedStaticDescription();

public:

    virtual ~AnyTimeSubscriptionInterrogationArg()
    {
        // Nothing to do.
    }

    virtual its::AsnObject* Clone() const
    {
        return new AnyTimeSubscriptionInterrogationArg(*this);
    }

    virtual std::string GetName() const
    { return "AnyTimeSubscriptionInterrogationArg"; }

    void SetSubscriberIdentity(SubscriberIdentity* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetSubscriberIdentityStaticDescription());
        AddElement(0, element);
    }

    void SetSubscriberIdentity(const SubscriberIdentity& element)
    {
        its::AsnObject& asnObject = const_cast<SubscriberIdentity&>(element);
        asnObject.SetDescription(GetSubscriberIdentityStaticDescription());
        AddElement(0, element);
    }

    const SubscriberIdentity& GetSubscriberIdentity() const
    {
        return static_cast<const SubscriberIdentity&> (ElementAt(0));
    }

    void SetRequestedSubscriptionInfo(RequestedSubscriptionInfo* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetRequestedSubscriptionInfoStaticDescription());
        AddElement(1, element);
    }

    void SetRequestedSubscriptionInfo(const RequestedSubscriptionInfo& element)
    {
        its::AsnObject& asnObject = const_cast<RequestedSubscriptionInfo&>(element);
        asnObject.SetDescription(GetRequestedSubscriptionInfoStaticDescription());
        AddElement(1, element);
    }

    const RequestedSubscriptionInfo& GetRequestedSubscriptionInfo() const
    {
        return static_cast<const RequestedSubscriptionInfo&> (ElementAt(1));
    }

    void SetGsmSCF_Address(ISDN_AddressString* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetGsmSCF_AddressStaticDescription());
        AddElement(2, element);
    }

    void SetGsmSCF_Address(const ISDN_AddressString& element)
    {
        its::AsnObject& asnObject = const_cast<ISDN_AddressString&>(element);
        asnObject.SetDescription(GetGsmSCF_AddressStaticDescription());
        AddElement(2, element);
    }

    const ISDN_AddressString& GetGsmSCF_Address() const
    {
        return static_cast<const ISDN_AddressString&> (ElementAt(2));
    }

    void SetExtensionContainer(ExtensionContainer* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetExtensionContainerStaticDescription());
        AddElement(3, element);
    }

    void SetExtensionContainer(const ExtensionContainer& element)
    {
        its::AsnObject& asnObject = const_cast<ExtensionContainer&>(element);
        asnObject.SetDescription(GetExtensionContainerStaticDescription());
        AddElement(3, element);
    }

    bool OptionExtensionContainer() const
    {
        return Contains(3);
    }

    const ExtensionContainer& GetExtensionContainer() const
    {
        ITS_REQUIRE(OptionExtensionContainer());
        return static_cast<const ExtensionContainer&> (ElementAt(3));
    }

    void SetLongFTN_Supported(LongFTN_Supported* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetLongFTN_SupportedStaticDescription());
        AddElement(4, element);
    }

    void SetLongFTN_Supported(const LongFTN_Supported& element)
    {
        its::AsnObject& asnObject = const_cast<LongFTN_Supported&>(element);
        asnObject.SetDescription(GetLongFTN_SupportedStaticDescription());
        AddElement(4, element);
    }

    bool OptionLongFTN_Supported() const
    {
        return Contains(4);
    }

    const LongFTN_Supported& GetLongFTN_Supported() const
    {
        ITS_REQUIRE(OptionLongFTN_Supported());
        return static_cast<const LongFTN_Supported&> (ElementAt(4));
    }

};



} // namespace.

#endif    // !defined(_MAP_V13_ANY_TIME_SUBSCRIPTION_INTERROGATION_ARG_H_)

