//
// Generated by IntelliAsnCC ASN.1 compiler (C, C++, Java).
//
// Do not edit!
//
//
//
// (C) 2000, 2001 IntelliNet Technologies Inc. All Rights Reserved.
//
//


#if !defined(_MAP_V2_BASIC_SERVICE_LIST_H_)
#define _MAP_V2_BASIC_SERVICE_LIST_H_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

#include <Asn.h>
#include <AsnObject.h>
#include <AsnDescObject.h>
#include <AsnError.h>

#include <AsnSequenceOf.h>
#include <AsnChoice.h>

#include <map_v2_basic_service_code.h>



namespace map_v2 {



class BasicServiceList : public its::AsnSequenceOf
{
public:


////////// Begin Nested Class //////////


        typedef map_v2::BasicServiceCode BasicServiceCode;


////////// End Nested Class //////////

    BasicServiceList() : its::AsnSequenceOf(false)
    {
        Initialize();
    }

    BasicServiceList(its::Octets& octets) : its::AsnSequenceOf(false)
    {
        Initialize();
        Decode(octets);
    }

    BasicServiceList(const BasicServiceList& rhs) : its::AsnSequenceOf(rhs)
    {
        // Nothing to do.
    }

    BasicServiceList(its::AsnDescObject* description) : its::AsnSequenceOf(description)
    {
        // Nothing to do.
    }

protected:

    void Initialize()
    {
        _description = GetStaticDescription();
    }

public:

    static its::AsnDescObject* GetStaticDescription();

    static its::AsnDescObject* GetBasicServiceCodeStaticDescription();

public:

    virtual ~BasicServiceList()
    {
        // Nothing to do.
    }

    virtual its::AsnObject* Clone() const
    {
        return new BasicServiceList(*this);
    }

    virtual std::string GetName() const
    { return "BasicServiceList"; }

    void AddElement(BasicServiceCode* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetBasicServiceCodeStaticDescription());
        AsnSequenceOf::AddElement(element);
    }

    void AddElement(const BasicServiceCode& element)
    {
        its::AsnObject& asnObject = const_cast<BasicServiceCode&>(element);
        asnObject.SetDescription(GetBasicServiceCodeStaticDescription());
        AsnSequenceOf::AddElement(element);
    }

    const BasicServiceCode& ElementAt(int index) const
    {
        return static_cast<const BasicServiceCode&> (AsnSequenceOf::ElementAt(index));
    }

};



} // namespace.

#endif    // !defined(_MAP_V2_BASIC_SERVICE_LIST_H_)

