//
// Generated by IntelliAsnCC ASN.1 compiler (C, C++, Java).
//
// Do not edit!
//
//
//
// (C) 2000, 2001 IntelliNet Technologies Inc. All Rights Reserved.
//
//


#if !defined(_MAP_V9_LOCATION_INFO_WITH_LMSI_H_)
#define _MAP_V9_LOCATION_INFO_WITH_LMSI_H_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

#include <Asn.h>
#include <AsnObject.h>
#include <AsnDescObject.h>
#include <AsnError.h>

#include <AsnSequence.h>
#include <AsnNull.h>
#include <AsnOctetString.h>
#include <AsnChoice.h>

#include <map_v9_isdn_address_string.h>
#include <map_v9_lmsi.h>
#include <map_v9_extension_container.h>
#include <map_v9_additional_number.h>



namespace map_v9 {



class LocationInfoWithLMSI : public its::AsnSequence
{
public:


////////// Begin Nested Class(es) //////////



    class GprsNodeIndicator : public its::AsnNull
    {
    public:

        GprsNodeIndicator() : its::AsnNull(false)
        {
            Initialize();
        }

        GprsNodeIndicator(its::Octets& octets) : its::AsnNull(false)
        {
            Initialize();
            Decode(octets);
        }

        GprsNodeIndicator(const GprsNodeIndicator& rhs) : its::AsnNull(rhs)
        {
            // Nothing to do.
        }

        GprsNodeIndicator(its::AsnDescObject* description) : its::AsnNull(description)
        {
            // Nothing to do.
        }

    protected:

        void Initialize()
        {
            _description = GetStaticDescription();
        }

    public:

        static its::AsnDescObject* GetStaticDescription();

    public:

        virtual ~GprsNodeIndicator()
        {
            // Nothing to do.
        }

        virtual its::AsnObject* Clone() const
        {
            return new GprsNodeIndicator(*this);
        }

        virtual std::string GetName() const
        { return "GprsNodeIndicator"; }

    };


        typedef map_v9::ISDN_AddressString ISDN_AddressString;


        typedef map_v9::LMSI LMSI;


        typedef map_v9::ExtensionContainer ExtensionContainer;


        typedef map_v9::Additional_Number Additional_Number;


////////// End Nested Class(es) //////////

    LocationInfoWithLMSI() : its::AsnSequence(5, false)
    {
        Initialize();
    }

    LocationInfoWithLMSI(its::Octets& octets) : its::AsnSequence(5, false)
    {
        Initialize();
        Decode(octets);
    }

    LocationInfoWithLMSI(const LocationInfoWithLMSI& rhs) : its::AsnSequence(rhs)
    {
        // Nothing to do.
    }

    LocationInfoWithLMSI(its::AsnDescObject* description) : its::AsnSequence(5, description)
    {
        // Nothing to do.
    }

protected:

    void Initialize()
    {
        _description = GetStaticDescription();
    }

public:

    static its::AsnDescObject* GetStaticDescription();

    static its::AsnDescObject* GetNetworkNode_NumberStaticDescription();
    static its::AsnDescObject* GetLmsiStaticDescription();
    static its::AsnDescObject* GetExtensionContainerStaticDescription();
    static its::AsnDescObject* GetGprsNodeIndicatorStaticDescription();
    static its::AsnDescObject* GetAdditional_NumberStaticDescription();

public:

    virtual ~LocationInfoWithLMSI()
    {
        // Nothing to do.
    }

    virtual its::AsnObject* Clone() const
    {
        return new LocationInfoWithLMSI(*this);
    }

    virtual std::string GetName() const
    { return "LocationInfoWithLMSI"; }

    void SetNetworkNode_Number(ISDN_AddressString* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetNetworkNode_NumberStaticDescription());
        AddElement(0, element);
    }

    void SetNetworkNode_Number(const ISDN_AddressString& element)
    {
        its::AsnObject& asnObject = const_cast<ISDN_AddressString&>(element);
        asnObject.SetDescription(GetNetworkNode_NumberStaticDescription());
        AddElement(0, element);
    }

    const ISDN_AddressString& GetNetworkNode_Number() const
    {
        return static_cast<const ISDN_AddressString&> (ElementAt(0));
    }

    void SetLmsi(LMSI* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetLmsiStaticDescription());
        AddElement(1, element);
    }

    void SetLmsi(const LMSI& element)
    {
        its::AsnObject& asnObject = const_cast<LMSI&>(element);
        asnObject.SetDescription(GetLmsiStaticDescription());
        AddElement(1, element);
    }

    bool OptionLmsi() const
    {
        return Contains(1);
    }

    const LMSI& GetLmsi() const
    {
        ITS_REQUIRE(OptionLmsi());
        return static_cast<const LMSI&> (ElementAt(1));
    }

    void SetExtensionContainer(ExtensionContainer* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetExtensionContainerStaticDescription());
        AddElement(2, element);
    }

    void SetExtensionContainer(const ExtensionContainer& element)
    {
        its::AsnObject& asnObject = const_cast<ExtensionContainer&>(element);
        asnObject.SetDescription(GetExtensionContainerStaticDescription());
        AddElement(2, element);
    }

    bool OptionExtensionContainer() const
    {
        return Contains(2);
    }

    const ExtensionContainer& GetExtensionContainer() const
    {
        ITS_REQUIRE(OptionExtensionContainer());
        return static_cast<const ExtensionContainer&> (ElementAt(2));
    }

    void SetGprsNodeIndicator(GprsNodeIndicator* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetGprsNodeIndicatorStaticDescription());
        AddElement(3, element);
    }

    void SetGprsNodeIndicator(const GprsNodeIndicator& element)
    {
        its::AsnObject& asnObject = const_cast<GprsNodeIndicator&>(element);
        asnObject.SetDescription(GetGprsNodeIndicatorStaticDescription());
        AddElement(3, element);
    }

    bool OptionGprsNodeIndicator() const
    {
        return Contains(3);
    }

    const GprsNodeIndicator& GetGprsNodeIndicator() const
    {
        ITS_REQUIRE(OptionGprsNodeIndicator());
        return static_cast<const GprsNodeIndicator&> (ElementAt(3));
    }

    void SetAdditional_Number(Additional_Number* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetAdditional_NumberStaticDescription());
        AddElement(4, element);
    }

    void SetAdditional_Number(const Additional_Number& element)
    {
        its::AsnObject& asnObject = const_cast<Additional_Number&>(element);
        asnObject.SetDescription(GetAdditional_NumberStaticDescription());
        AddElement(4, element);
    }

    bool OptionAdditional_Number() const
    {
        return Contains(4);
    }

    const Additional_Number& GetAdditional_Number() const
    {
        ITS_REQUIRE(OptionAdditional_Number());
        return static_cast<const Additional_Number&> (ElementAt(4));
    }

};



} // namespace.

#endif    // !defined(_MAP_V9_LOCATION_INFO_WITH_LMSI_H_)

