//
// Generated by IntelliAsnCC ASN.1 compiler (C, C++, Java).
//
// Do not edit!
//
//
//
// (C) 2000, 2001 IntelliNet Technologies Inc. All Rights Reserved.
//
//


#if !defined(_MAP_V13_MT_FORWARD_SM_VGCS_ARG_H_)
#define _MAP_V13_MT_FORWARD_SM_VGCS_ARG_H_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

#include <Asn.h>
#include <AsnObject.h>
#include <AsnDescObject.h>
#include <AsnError.h>

#include <AsnSequence.h>
#include <AsnOctetString.h>
#include <AsnChoice.h>

#include <map_v13_asci_call_reference.h>
#include <map_v13_sm_rp_oa.h>
#include <map_v13_signal_info.h>
#include <map_v13_extension_container.h>



namespace map_v13 {



class MT_ForwardSM_VGCS_Arg : public its::AsnSequence
{
public:


////////// Begin Nested Class(es) //////////


        typedef map_v13::ASCI_CallReference ASCI_CallReference;


        typedef map_v13::SM_RP_OA SM_RP_OA;


        typedef map_v13::SignalInfo SignalInfo;


        typedef map_v13::ExtensionContainer ExtensionContainer;


////////// End Nested Class(es) //////////

    MT_ForwardSM_VGCS_Arg() : its::AsnSequence(4, false)
    {
        Initialize();
    }

    MT_ForwardSM_VGCS_Arg(its::Octets& octets) : its::AsnSequence(4, false)
    {
        Initialize();
        Decode(octets);
    }

    MT_ForwardSM_VGCS_Arg(const MT_ForwardSM_VGCS_Arg& rhs) : its::AsnSequence(rhs)
    {
        // Nothing to do.
    }

    MT_ForwardSM_VGCS_Arg(its::AsnDescObject* description) : its::AsnSequence(4, description)
    {
        // Nothing to do.
    }

protected:

    void Initialize()
    {
        _description = GetStaticDescription();
    }

public:

    static its::AsnDescObject* GetStaticDescription();

    static its::AsnDescObject* GetAsciCallReferenceStaticDescription();
    static its::AsnDescObject* GetSm_RP_OAStaticDescription();
    static its::AsnDescObject* GetSm_RP_UIStaticDescription();
    static its::AsnDescObject* GetExtensionContainerStaticDescription();

public:

    virtual ~MT_ForwardSM_VGCS_Arg()
    {
        // Nothing to do.
    }

    virtual its::AsnObject* Clone() const
    {
        return new MT_ForwardSM_VGCS_Arg(*this);
    }

    virtual std::string GetName() const
    { return "MT_ForwardSM_VGCS_Arg"; }

    void SetAsciCallReference(ASCI_CallReference* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetAsciCallReferenceStaticDescription());
        AddElement(0, element);
    }

    void SetAsciCallReference(const ASCI_CallReference& element)
    {
        its::AsnObject& asnObject = const_cast<ASCI_CallReference&>(element);
        asnObject.SetDescription(GetAsciCallReferenceStaticDescription());
        AddElement(0, element);
    }

    const ASCI_CallReference& GetAsciCallReference() const
    {
        return static_cast<const ASCI_CallReference&> (ElementAt(0));
    }

    void SetSm_RP_OA(SM_RP_OA* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetSm_RP_OAStaticDescription());
        AddElement(1, element);
    }

    void SetSm_RP_OA(const SM_RP_OA& element)
    {
        its::AsnObject& asnObject = const_cast<SM_RP_OA&>(element);
        asnObject.SetDescription(GetSm_RP_OAStaticDescription());
        AddElement(1, element);
    }

    const SM_RP_OA& GetSm_RP_OA() const
    {
        return static_cast<const SM_RP_OA&> (ElementAt(1));
    }

    void SetSm_RP_UI(SignalInfo* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetSm_RP_UIStaticDescription());
        AddElement(2, element);
    }

    void SetSm_RP_UI(const SignalInfo& element)
    {
        its::AsnObject& asnObject = const_cast<SignalInfo&>(element);
        asnObject.SetDescription(GetSm_RP_UIStaticDescription());
        AddElement(2, element);
    }

    const SignalInfo& GetSm_RP_UI() const
    {
        return static_cast<const SignalInfo&> (ElementAt(2));
    }

    void SetExtensionContainer(ExtensionContainer* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetExtensionContainerStaticDescription());
        AddElement(3, element);
    }

    void SetExtensionContainer(const ExtensionContainer& element)
    {
        its::AsnObject& asnObject = const_cast<ExtensionContainer&>(element);
        asnObject.SetDescription(GetExtensionContainerStaticDescription());
        AddElement(3, element);
    }

    bool OptionExtensionContainer() const
    {
        return Contains(3);
    }

    const ExtensionContainer& GetExtensionContainer() const
    {
        ITS_REQUIRE(OptionExtensionContainer());
        return static_cast<const ExtensionContainer&> (ElementAt(3));
    }

};



} // namespace.

#endif    // !defined(_MAP_V13_MT_FORWARD_SM_VGCS_ARG_H_)

