//
// Generated by IntelliAsnCC ASN.1 compiler (C, C++, Java).
//
// Do not edit!
//
//
//
// (C) 2000, 2001 IntelliNet Technologies Inc. All Rights Reserved.
//
//


#if !defined(_MAP_V9_SHORT_TERM_DENIAL_PARAM_H_)
#define _MAP_V9_SHORT_TERM_DENIAL_PARAM_H_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

#include <Asn.h>
#include <AsnObject.h>
#include <AsnDescObject.h>
#include <AsnError.h>

#include <AsnSequence.h>



namespace map_v9 {



class ShortTermDenialParam : public its::AsnSequence
{
public:


////////// Begin Nested Class(es) //////////


////////// End Nested Class(es) //////////

    ShortTermDenialParam() : its::AsnSequence(0, false)
    {
        Initialize();
    }

    ShortTermDenialParam(its::Octets& octets) : its::AsnSequence(0, false)
    {
        Initialize();
        Decode(octets);
    }

    ShortTermDenialParam(const ShortTermDenialParam& rhs) : its::AsnSequence(rhs)
    {
        // Nothing to do.
    }

    ShortTermDenialParam(its::AsnDescObject* description) : its::AsnSequence(0, description)
    {
        // Nothing to do.
    }

protected:

    void Initialize()
    {
        _description = GetStaticDescription();
    }

public:

    static its::AsnDescObject* GetStaticDescription();

public:

    virtual ~ShortTermDenialParam()
    {
        // Nothing to do.
    }

    virtual its::AsnObject* Clone() const
    {
        return new ShortTermDenialParam(*this);
    }

    virtual std::string GetName() const
    { return "ShortTermDenialParam"; }

};



} // namespace.

#endif    // !defined(_MAP_V9_SHORT_TERM_DENIAL_PARAM_H_)

