//
// Generated by IntelliAsnCC ASN.1 compiler (C, C++, Java).
//
// Do not edit!
//
//
//
// (C) 2000, 2001 IntelliNet Technologies Inc. All Rights Reserved.
//
//


#if !defined(_MAP_V2_SENT_PARAMETER_LIST_H_)
#define _MAP_V2_SENT_PARAMETER_LIST_H_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

#include <Asn.h>
#include <AsnObject.h>
#include <AsnDescObject.h>
#include <AsnError.h>

#include <AsnSequenceOf.h>
#include <AsnChoice.h>

#include <map_v2_sent_parameter.h>



namespace map_v2 {



class SentParameterList : public its::AsnSequenceOf
{
public:


////////// Begin Nested Class //////////


        typedef map_v2::SentParameter SentParameter;


////////// End Nested Class //////////

    SentParameterList() : its::AsnSequenceOf(false)
    {
        Initialize();
    }

    SentParameterList(its::Octets& octets) : its::AsnSequenceOf(false)
    {
        Initialize();
        Decode(octets);
    }

    SentParameterList(const SentParameterList& rhs) : its::AsnSequenceOf(rhs)
    {
        // Nothing to do.
    }

    SentParameterList(its::AsnDescObject* description) : its::AsnSequenceOf(description)
    {
        // Nothing to do.
    }

protected:

    void Initialize()
    {
        _description = GetStaticDescription();
    }

public:

    static its::AsnDescObject* GetStaticDescription();

    static its::AsnDescObject* GetSentParameterStaticDescription();

public:

    virtual ~SentParameterList()
    {
        // Nothing to do.
    }

    virtual its::AsnObject* Clone() const
    {
        return new SentParameterList(*this);
    }

    virtual std::string GetName() const
    { return "SentParameterList"; }

    void AddElement(SentParameter* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetSentParameterStaticDescription());
        AsnSequenceOf::AddElement(element);
    }

    void AddElement(const SentParameter& element)
    {
        its::AsnObject& asnObject = const_cast<SentParameter&>(element);
        asnObject.SetDescription(GetSentParameterStaticDescription());
        AsnSequenceOf::AddElement(element);
    }

    const SentParameter& ElementAt(int index) const
    {
        return static_cast<const SentParameter&> (AsnSequenceOf::ElementAt(index));
    }

};



} // namespace.

#endif    // !defined(_MAP_V2_SENT_PARAMETER_LIST_H_)

