//
// Generated by IntelliAsnCC ASN.1 compiler (C, C++, Java).
//
// Do not edit!
//
//
//
// (C) 2000, 2001 IntelliNet Technologies Inc. All Rights Reserved.
//
//


#if !defined(_MAP_V2_TELESERVICE_LIST_H_)
#define _MAP_V2_TELESERVICE_LIST_H_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

#include <Asn.h>
#include <AsnObject.h>
#include <AsnDescObject.h>
#include <AsnError.h>

#include <AsnSequenceOf.h>
#include <AsnOctetString.h>

#include <map_v2_teleservice_code.h>



namespace map_v2 {



class TeleserviceList : public its::AsnSequenceOf
{
public:


////////// Begin Nested Class //////////


        typedef map_v2::TeleserviceCode TeleserviceCode;


////////// End Nested Class //////////

    TeleserviceList() : its::AsnSequenceOf(false)
    {
        Initialize();
    }

    TeleserviceList(its::Octets& octets) : its::AsnSequenceOf(false)
    {
        Initialize();
        Decode(octets);
    }

    TeleserviceList(const TeleserviceList& rhs) : its::AsnSequenceOf(rhs)
    {
        // Nothing to do.
    }

    TeleserviceList(its::AsnDescObject* description) : its::AsnSequenceOf(description)
    {
        // Nothing to do.
    }

protected:

    void Initialize()
    {
        _description = GetStaticDescription();
    }

public:

    static its::AsnDescObject* GetStaticDescription();

    static its::AsnDescObject* GetTeleserviceCodeStaticDescription();

public:

    virtual ~TeleserviceList()
    {
        // Nothing to do.
    }

    virtual its::AsnObject* Clone() const
    {
        return new TeleserviceList(*this);
    }

    virtual std::string GetName() const
    { return "TeleserviceList"; }

    void AddElement(TeleserviceCode* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetTeleserviceCodeStaticDescription());
        AsnSequenceOf::AddElement(element);
    }

    void AddElement(const TeleserviceCode& element)
    {
        its::AsnObject& asnObject = const_cast<TeleserviceCode&>(element);
        asnObject.SetDescription(GetTeleserviceCodeStaticDescription());
        AsnSequenceOf::AddElement(element);
    }

    const TeleserviceCode& ElementAt(int index) const
    {
        return static_cast<const TeleserviceCode&> (AsnSequenceOf::ElementAt(index));
    }

};



} // namespace.

#endif    // !defined(_MAP_V2_TELESERVICE_LIST_H_)

