//
// Generated by IntelliAsnCC ASN.1 compiler (C, C++, Java).
//
// Do not edit!
//
//
//
// (C) 2000, 2001 IntelliNet Technologies Inc. All Rights Reserved.
//
//


#if !defined(_MAP_V13_EXTENSIBLE_CALL_BARRED_PARAM_H_)
#define _MAP_V13_EXTENSIBLE_CALL_BARRED_PARAM_H_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

#include <Asn.h>
#include <AsnObject.h>
#include <AsnDescObject.h>
#include <AsnError.h>

#include <AsnSequence.h>
#include <AsnNull.h>
#include <AsnEnumerated.h>

#include <map_v13_call_barring_cause.h>
#include <map_v13_extension_container.h>



namespace map_v13 {



class ExtensibleCallBarredParam : public its::AsnSequence
{
public:


////////// Begin Nested Class(es) //////////



    class UnauthorisedMessageOriginator : public its::AsnNull
    {
    public:

        UnauthorisedMessageOriginator() : its::AsnNull(false)
        {
            Initialize();
        }

        UnauthorisedMessageOriginator(its::Octets& octets) : its::AsnNull(false)
        {
            Initialize();
            Decode(octets);
        }

        UnauthorisedMessageOriginator(const UnauthorisedMessageOriginator& rhs) : its::AsnNull(rhs)
        {
            // Nothing to do.
        }

        UnauthorisedMessageOriginator(its::AsnDescObject* description) : its::AsnNull(description)
        {
            // Nothing to do.
        }

    protected:

        void Initialize()
        {
            _description = GetStaticDescription();
        }

    public:

        static its::AsnDescObject* GetStaticDescription();

    public:

        virtual ~UnauthorisedMessageOriginator()
        {
            // Nothing to do.
        }

        virtual its::AsnObject* Clone() const
        {
            return new UnauthorisedMessageOriginator(*this);
        }

        virtual std::string GetName() const
        { return "UnauthorisedMessageOriginator"; }

    };


        typedef map_v13::CallBarringCause CallBarringCause;


        typedef map_v13::ExtensionContainer ExtensionContainer;


////////// End Nested Class(es) //////////

    ExtensibleCallBarredParam() : its::AsnSequence(3, false)
    {
        Initialize();
    }

    ExtensibleCallBarredParam(its::Octets& octets) : its::AsnSequence(3, false)
    {
        Initialize();
        Decode(octets);
    }

    ExtensibleCallBarredParam(const ExtensibleCallBarredParam& rhs) : its::AsnSequence(rhs)
    {
        // Nothing to do.
    }

    ExtensibleCallBarredParam(its::AsnDescObject* description) : its::AsnSequence(3, description)
    {
        // Nothing to do.
    }

protected:

    void Initialize()
    {
        _description = GetStaticDescription();
    }

public:

    static its::AsnDescObject* GetStaticDescription();

    static its::AsnDescObject* GetCallBarringCauseStaticDescription();
    static its::AsnDescObject* GetExtensionContainerStaticDescription();
    static its::AsnDescObject* GetUnauthorisedMessageOriginatorStaticDescription();

public:

    virtual ~ExtensibleCallBarredParam()
    {
        // Nothing to do.
    }

    virtual its::AsnObject* Clone() const
    {
        return new ExtensibleCallBarredParam(*this);
    }

    virtual std::string GetName() const
    { return "ExtensibleCallBarredParam"; }

    void SetCallBarringCause(CallBarringCause* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetCallBarringCauseStaticDescription());
        AddElement(0, element);
    }

    void SetCallBarringCause(const CallBarringCause& element)
    {
        its::AsnObject& asnObject = const_cast<CallBarringCause&>(element);
        asnObject.SetDescription(GetCallBarringCauseStaticDescription());
        AddElement(0, element);
    }

    bool OptionCallBarringCause() const
    {
        return Contains(0);
    }

    const CallBarringCause& GetCallBarringCause() const
    {
        ITS_REQUIRE(OptionCallBarringCause());
        return static_cast<const CallBarringCause&> (ElementAt(0));
    }

    void SetExtensionContainer(ExtensionContainer* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetExtensionContainerStaticDescription());
        AddElement(1, element);
    }

    void SetExtensionContainer(const ExtensionContainer& element)
    {
        its::AsnObject& asnObject = const_cast<ExtensionContainer&>(element);
        asnObject.SetDescription(GetExtensionContainerStaticDescription());
        AddElement(1, element);
    }

    bool OptionExtensionContainer() const
    {
        return Contains(1);
    }

    const ExtensionContainer& GetExtensionContainer() const
    {
        ITS_REQUIRE(OptionExtensionContainer());
        return static_cast<const ExtensionContainer&> (ElementAt(1));
    }

    void SetUnauthorisedMessageOriginator(UnauthorisedMessageOriginator* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetUnauthorisedMessageOriginatorStaticDescription());
        AddElement(2, element);
    }

    void SetUnauthorisedMessageOriginator(const UnauthorisedMessageOriginator& element)
    {
        its::AsnObject& asnObject = const_cast<UnauthorisedMessageOriginator&>(element);
        asnObject.SetDescription(GetUnauthorisedMessageOriginatorStaticDescription());
        AddElement(2, element);
    }

    bool OptionUnauthorisedMessageOriginator() const
    {
        return Contains(2);
    }

    const UnauthorisedMessageOriginator& GetUnauthorisedMessageOriginator() const
    {
        ITS_REQUIRE(OptionUnauthorisedMessageOriginator());
        return static_cast<const UnauthorisedMessageOriginator&> (ElementAt(2));
    }

};



} // namespace.

#endif    // !defined(_MAP_V13_EXTENSIBLE_CALL_BARRED_PARAM_H_)

