//
// Generated by IntelliAsnCC ASN.1 compiler (C, C++, Java).
//
// Do not edit!
//
//
//
// (C) 2000, 2001 IntelliNet Technologies Inc. All Rights Reserved.
//
//


#if !defined(_MAP_V13_GERAN_CLASSMARK_H_)
#define _MAP_V13_GERAN_CLASSMARK_H_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

#include <Asn.h>
#include <AsnObject.h>
#include <AsnDescObject.h>
#include <AsnError.h>

#include <AsnOctetString.h>



namespace map_v13 {



class GERAN_Classmark : public its::AsnOctetString
{
public:

    GERAN_Classmark() : its::AsnOctetString(false)
    {
        Initialize();
    }

    GERAN_Classmark(const std::vector<byte>& array) : its::AsnOctetString(array, false)
    {
        Initialize();
    }

    GERAN_Classmark(its::Octets& octets) : its::AsnOctetString(false)
    {
        Initialize();
        Decode(octets);
    }

    GERAN_Classmark(const GERAN_Classmark& rhs) : its::AsnOctetString(rhs)
    {
        // Nothing to do.
    }

    GERAN_Classmark(its::AsnDescObject* description) : its::AsnOctetString(description)
    {
        // Nothing to do.
    }

    GERAN_Classmark(its::AsnDescObject* description, const std::vector<byte>& array) : its::AsnOctetString(description, array)
    {
        // Nothing to do.
    }

protected:

    void Initialize()
    {
        _description = GetStaticDescription();
    }

public:

    static its::AsnDescObject* GetStaticDescription();

public:

    virtual ~GERAN_Classmark()
    {
        // Nothing to do.
    }

    virtual its::AsnObject* Clone() const
    {
        return new GERAN_Classmark(*this);
    }

    virtual std::string GetName() const
    { return "GERAN_Classmark"; }

};



} // namespace.

#endif    // !defined(_MAP_V13_GERAN_CLASSMARK_H_)

