//
// Generated by IntelliAsnCC ASN.1 compiler (C, C++, Java).
//
// Do not edit!
//
//
//
// (C) 2000, 2001 IntelliNet Technologies Inc. All Rights Reserved.
//
//


#if !defined(_MAP_V9_UNKNOWN_SUBSCRIBER_PARAM_H_)
#define _MAP_V9_UNKNOWN_SUBSCRIBER_PARAM_H_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

#include <Asn.h>
#include <AsnObject.h>
#include <AsnDescObject.h>
#include <AsnError.h>

#include <AsnSequence.h>
#include <AsnEnumerated.h>

#include <map_v9_extension_container.h>
#include <map_v9_unknown_subscriber_diagnostic.h>



namespace map_v9 {



class UnknownSubscriberParam : public its::AsnSequence
{
public:


////////// Begin Nested Class(es) //////////


        typedef map_v9::ExtensionContainer ExtensionContainer;


        typedef map_v9::UnknownSubscriberDiagnostic UnknownSubscriberDiagnostic;


////////// End Nested Class(es) //////////

    UnknownSubscriberParam() : its::AsnSequence(2, false)
    {
        Initialize();
    }

    UnknownSubscriberParam(its::Octets& octets) : its::AsnSequence(2, false)
    {
        Initialize();
        Decode(octets);
    }

    UnknownSubscriberParam(const UnknownSubscriberParam& rhs) : its::AsnSequence(rhs)
    {
        // Nothing to do.
    }

    UnknownSubscriberParam(its::AsnDescObject* description) : its::AsnSequence(2, description)
    {
        // Nothing to do.
    }

protected:

    void Initialize()
    {
        _description = GetStaticDescription();
    }

public:

    static its::AsnDescObject* GetStaticDescription();

    static its::AsnDescObject* GetExtensionContainerStaticDescription();
    static its::AsnDescObject* GetUnknownSubscriberDiagnosticStaticDescription();

public:

    virtual ~UnknownSubscriberParam()
    {
        // Nothing to do.
    }

    virtual its::AsnObject* Clone() const
    {
        return new UnknownSubscriberParam(*this);
    }

    virtual std::string GetName() const
    { return "UnknownSubscriberParam"; }

    void SetExtensionContainer(ExtensionContainer* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetExtensionContainerStaticDescription());
        AddElement(0, element);
    }

    void SetExtensionContainer(const ExtensionContainer& element)
    {
        its::AsnObject& asnObject = const_cast<ExtensionContainer&>(element);
        asnObject.SetDescription(GetExtensionContainerStaticDescription());
        AddElement(0, element);
    }

    bool OptionExtensionContainer() const
    {
        return Contains(0);
    }

    const ExtensionContainer& GetExtensionContainer() const
    {
        ITS_REQUIRE(OptionExtensionContainer());
        return static_cast<const ExtensionContainer&> (ElementAt(0));
    }

    void SetUnknownSubscriberDiagnostic(UnknownSubscriberDiagnostic* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetUnknownSubscriberDiagnosticStaticDescription());
        AddElement(1, element);
    }

    void SetUnknownSubscriberDiagnostic(const UnknownSubscriberDiagnostic& element)
    {
        its::AsnObject& asnObject = const_cast<UnknownSubscriberDiagnostic&>(element);
        asnObject.SetDescription(GetUnknownSubscriberDiagnosticStaticDescription());
        AddElement(1, element);
    }

    bool OptionUnknownSubscriberDiagnostic() const
    {
        return Contains(1);
    }

    const UnknownSubscriberDiagnostic& GetUnknownSubscriberDiagnostic() const
    {
        ITS_REQUIRE(OptionUnknownSubscriberDiagnostic());
        return static_cast<const UnknownSubscriberDiagnostic&> (ElementAt(1));
    }

};



} // namespace.

#endif    // !defined(_MAP_V9_UNKNOWN_SUBSCRIBER_PARAM_H_)

