//
// Generated by IntelliAsnCC ASN.1 compiler (C, C++, Java).
//
// Do not edit!
//
//
//
// (C) 2000, 2001 IntelliNet Technologies Inc. All Rights Reserved.
//
//


#if !defined(_MAP_V9_MSC_S_EVENT_LIST_H_)
#define _MAP_V9_MSC_S_EVENT_LIST_H_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

#include <Asn.h>
#include <AsnObject.h>
#include <AsnDescObject.h>
#include <AsnError.h>

#include <AsnBitString.h>



namespace map_v9 {



class MSC_S_EventList : public its::AsnBitString
{
public:

    MSC_S_EventList() : its::AsnBitString(false)
    {
        Initialize();
    }

    MSC_S_EventList(const std::vector<bool>& array) : its::AsnBitString(array, false)
    {
        Initialize();
    }

    MSC_S_EventList(its::Octets& octets) : its::AsnBitString(false)
    {
        Initialize();
        Decode(octets);
    }

    MSC_S_EventList(const MSC_S_EventList& rhs) : its::AsnBitString(rhs)
    {
        // Nothing to do.
    }

    MSC_S_EventList(its::AsnDescObject* description) : its::AsnBitString(description)
    {
        // Nothing to do.
    }

    MSC_S_EventList(its::AsnDescObject* description, const std::vector<bool>& array) : its::AsnBitString(description, array)
    {
        // Nothing to do.
    }

protected:

    void Initialize()
    {
        _description = GetStaticDescription();
    }

public:

    static its::AsnDescObject* GetStaticDescription();

public:

    virtual ~MSC_S_EventList()
    {
        // Nothing to do.
    }

    virtual its::AsnObject* Clone() const
    {
        return new MSC_S_EventList(*this);
    }

    virtual std::string GetName() const
    { return "MSC_S_EventList"; }

    void SetSs()
    { Set(4); }

    void ResetSs()
    { Reset(4); }

    bool IsSsSet() const
    { return IsSet(4); }

    bool IsSsDefined() const
    { return 4 < GetSize(); }

    void SetHandovers()
    { Set(3); }

    void ResetHandovers()
    { Reset(3); }

    bool IsHandoversSet() const
    { return IsSet(3); }

    bool IsHandoversDefined() const
    { return 3 < GetSize(); }

    void SetLu_imsiAttach_imsiDetach()
    { Set(2); }

    void ResetLu_imsiAttach_imsiDetach()
    { Reset(2); }

    bool IsLu_imsiAttach_imsiDetachSet() const
    { return IsSet(2); }

    bool IsLu_imsiAttach_imsiDetachDefined() const
    { return 2 < GetSize(); }

    void SetMo_mt_sms()
    { Set(1); }

    void ResetMo_mt_sms()
    { Reset(1); }

    bool IsMo_mt_smsSet() const
    { return IsSet(1); }

    bool IsMo_mt_smsDefined() const
    { return 1 < GetSize(); }

    void SetMo_mtCall()
    { Set(0); }

    void ResetMo_mtCall()
    { Reset(0); }

    bool IsMo_mtCallSet() const
    { return IsSet(0); }

    bool IsMo_mtCallDefined() const
    { return 0 < GetSize(); }

};



} // namespace.

#endif    // !defined(_MAP_V9_MSC_S_EVENT_LIST_H_)

