//
// Generated by IntelliAsnCC ASN.1 compiler (C, C++, Java).
//
// Do not edit!
//
//
//
// (C) 2000, 2001 IntelliNet Technologies Inc. All Rights Reserved.
//
//


#if !defined(_MAP_V13_RAN_TECHNOLOGY_H_)
#define _MAP_V13_RAN_TECHNOLOGY_H_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

#include <Asn.h>
#include <AsnObject.h>
#include <AsnDescObject.h>
#include <AsnError.h>

#include <AsnEnumerated.h>



namespace map_v13 {



class RAN_Technology : public its::AsnEnumerated
{
public:

    RAN_Technology() : its::AsnEnumerated(false)
    {
        Initialize();
    }

    RAN_Technology(long value) : its::AsnEnumerated(value, false)
    {
        Initialize();
    }

    RAN_Technology(its::Octets& octets) : its::AsnEnumerated(false)
    {
        Initialize();
        Decode(octets);
    }

    RAN_Technology(const RAN_Technology& rhs) : its::AsnEnumerated(rhs)
    {
        // Nothing to do.
    }

    RAN_Technology(its::AsnDescObject* description) : its::AsnEnumerated(description)
    {
        // Nothing to do.
    }

    RAN_Technology(its::AsnDescObject* description, long value) : its::AsnEnumerated(description, value)
    {
        // Nothing to do.
    }

protected:

    void Initialize()
    {
        _description = GetStaticDescription();
    }

public:

    static its::AsnDescObject* GetStaticDescription();

public:

    virtual ~RAN_Technology()
    {
        // Nothing to do.
    }

    virtual its::AsnObject* Clone() const
    {
        return new RAN_Technology(*this);
    }

    virtual std::string GetName() const
    { return "RAN_Technology"; }

    virtual long Get(const std::string& valueName) const;

    virtual std::string Get(long value) const;

    virtual std::string GetExt(long value) const;

    enum {
        RAN_TECHNOLOGY_GSM = 0,
        RAN_TECHNOLOGY_UMTS = 1

    };

    void SetGsm()
    { _value = 0; }

    bool IsGsm() const
    { return _value == 0; }

    void SetUmts()
    { _value = 1; }

    bool IsUmts() const
    { return _value == 1; }

};



} // namespace.

#endif    // !defined(_MAP_V13_RAN_TECHNOLOGY_H_)

