//
// Generated by IntelliAsnCC ASN.1 compiler (C, C++, Java).
//
// Do not edit!
//
//
//
// (C) 2000, 2001 IntelliNet Technologies Inc. All Rights Reserved.
//
//


#if !defined(_MAP_V13_IST_SUPPORT_INDICATOR_H_)
#define _MAP_V13_IST_SUPPORT_INDICATOR_H_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

#include <Asn.h>
#include <AsnObject.h>
#include <AsnDescObject.h>
#include <AsnError.h>

#include <AsnEnumerated.h>



namespace map_v13 {



class IST_SupportIndicator : public its::AsnEnumerated
{
public:

    IST_SupportIndicator() : its::AsnEnumerated(false)
    {
        Initialize();
    }

    IST_SupportIndicator(long value) : its::AsnEnumerated(value, false)
    {
        Initialize();
    }

    IST_SupportIndicator(its::Octets& octets) : its::AsnEnumerated(false)
    {
        Initialize();
        Decode(octets);
    }

    IST_SupportIndicator(const IST_SupportIndicator& rhs) : its::AsnEnumerated(rhs)
    {
        // Nothing to do.
    }

    IST_SupportIndicator(its::AsnDescObject* description) : its::AsnEnumerated(description)
    {
        // Nothing to do.
    }

    IST_SupportIndicator(its::AsnDescObject* description, long value) : its::AsnEnumerated(description, value)
    {
        // Nothing to do.
    }

protected:

    void Initialize()
    {
        _description = GetStaticDescription();
    }

public:

    static its::AsnDescObject* GetStaticDescription();

public:

    virtual ~IST_SupportIndicator()
    {
        // Nothing to do.
    }

    virtual its::AsnObject* Clone() const
    {
        return new IST_SupportIndicator(*this);
    }

    virtual std::string GetName() const
    { return "IST_SupportIndicator"; }

    virtual long Get(const std::string& valueName) const;

    virtual std::string Get(long value) const;

    virtual std::string GetExt(long value) const;

    enum {
        IST_SUPPORT_INDICATOR_BASIC_IST_SUPPORTED = 0,
        IST_SUPPORT_INDICATOR_IST_COMMAND_SUPPORTED = 1

    };

    void SetBasicISTSupported()
    { _value = 0; }

    bool IsBasicISTSupported() const
    { return _value == 0; }

    void SetIstCommandSupported()
    { _value = 1; }

    bool IsIstCommandSupported() const
    { return _value == 1; }

};



} // namespace.

#endif    // !defined(_MAP_V13_IST_SUPPORT_INDICATOR_H_)

