/*********************************-*-C-*-************************************
 *                                                                          *
 *             Copyright 1997,1998 IntelliNet Technologies, Inc.            *
 *                            All Rights Reserved.                          *
 *             Manufactured in the United States of America.                *
 *       1990 W. New Haven Ste. 312, Melbourne, Florida, 32904 U.S.A.       *
 *                                                                          *
 *   This product and related documentation is protected by copyright and   *
 *   distributed under licenses restricting its use, copying, distribution  *
 *   and decompilation.  No part of this product or related documentation   *
 *   may be reproduced in any form by any means without prior written       *
 *   authorization of IntelliNet Technologies and its licensors, if any.    *
 *                                                                          *
 *   RESTRICTED RIGHTS LEGEND:  Use, duplication, or disclosure by the      *
 *   government is subject to restrictions as set forth in subparagraph     *
 *   (c)(1)(ii) of the Rights in Technical Data and Computer Software       *
 *   clause at DFARS 252.227-7013 and FAR 52.227-19.                        *
 *                                                                          *
 ****************************************************************************
 *                                                                          *
 * CONTRACT: INTERNAL                                                       *
 *                                                                          *
 ****************************************************************************
 *
 *  ID: $Id: snmm_sn.h,v 9.1 2005/03/23 12:52:32 cvsadmin Exp $
 *
 * LOG: $Log: snmm_sn.h,v $
 * LOG: Revision 9.1  2005/03/23 12:52:32  cvsadmin
 * LOG: Begin PR6.5
 * LOG:
 * LOG: Revision 8.2  2005/03/21 13:50:32  cvsadmin
 * LOG: PR6.4.2 Source Propagated to Current
 * LOG:
 * LOG: Revision 7.1.46.1  2004/12/16 02:44:09  randresol
 * LOG: Add JAPAN variant implementation
 * LOG:
 * LOG: Revision 7.1.42.1  2004/10/25 20:39:56  randresol
 * LOG: Start Implementation for Japan SS7
 * LOG:
 * LOG: Revision 7.1  2002/08/26 22:09:31  mmiers
 * LOG: Begin PR6.2
 * LOG:
 * LOG: Revision 6.3  2002/08/16 22:09:27  mmiers
 * LOG: Add the China variant
 * LOG:
 * LOG: Revision 6.2  2002/07/03 16:14:33  mmiers
 * LOG: Add china family
 * LOG:
 * LOG: Revision 6.1  2002/02/28 16:14:03  mmiers
 * LOG: Begin PR7.
 * LOG:
 * LOG: Revision 5.3  2002/01/09 21:21:58  mmiers
 * LOG: Update for M2PA.  It (and SAAL) require larger BSNT fields
 * LOG: (16 and 24 bits, respectively).  Update SNMM to reflect this,
 * LOG: additional updates to SUPPORT for M2PA.
 * LOG:
 * LOG: Revision 5.2  2001/09/11 22:46:06  mmiers
 * LOG: Version strings.
 * LOG:
 * LOG: Revision 5.1  2001/08/16 20:45:52  mmiers
 * LOG: Start PR6.
 * LOG:
 * LOG: Revision 4.2  2001/06/21 01:04:48  mmiers
 * LOG: Make sure files end with newline
 * LOG:
 * LOG: Revision 4.1  2001/06/20 17:09:49  mmiers
 * LOG: The great namespace split, part two.  Also a bug fix to support.
 * LOG:
 *
 *****************************************************************************/

#ifndef _ITS_SNMM_SN_H_
#define _ITS_SNMM_SN_H_

#ident "$Id: snmm_sn.h,v 9.1 2005/03/23 12:52:32 cvsadmin Exp $"

/*
 * commonality
 */
#if defined(CCITT)

#define SNMM_HEADING_CODE_0_MASK    SNMM_HEADING_CODE_0_MASK_CCITT
#define SNMM_HEADING_CODE_1_MASK    SNMM_HEADING_CODE_1_MASK_CCITT

#define SNMM_HC0_SPARE  SNMM_HC0_SPARE_CCITT
#define SNMM_HC0_CHM    SNMM_HC0_CHM_CCITT
#define SNMM_HC0_ECM    SNMM_HC0_ECM_CCITT
#define SNMM_HC0_FCM    SNMM_HC0_FCM_CCITT
#define SNMM_HC0_TFM    SNMM_HC0_TFM_CCITT
#define SNMM_HC0_RSM    SNMM_HC0_RSM_CCITT
#define SNMM_HC0_MIM    SNMM_HC0_MIM_CCITT
#define SNMM_HC0_TRM    SNMM_HC0_TRM_CCITT
#define SNMM_HC0_DLM    SNMM_HC0_DLM_CCITT
#define SNMM_HC0_UFC    SNMM_HC0_UFC_CCITT

#define SNMM_HC1_COO    SNMM_HC1_COO_CCITT
#define SNMM_HC1_COA    SNMM_HC1_COA_CCITT
#define SNMM_HC1_XCO    SNMM_HC1_XCO_CCITT
#define SNMM_HC1_XCA    SNMM_HC1_XCA_CCITT
#define SNMM_HC1_CBD    SNMM_HC1_CBD_CCITT
#define SNMM_HC1_CBA    SNMM_HC1_CBA_CCITT
#define SNMM_HC1_ECO    SNMM_HC1_ECO_CCITT
#define SNMM_HC1_ECA    SNMM_HC1_ECA_CCITT
#define SNMM_HC1_TFP    SNMM_HC1_TFP_CCITT
#define SNMM_HC1_TCP    SNMM_HC1_TCP_CCITT
#define SNMM_HC1_TFR    SNMM_HC1_TFR_CCITT
#define SNMM_HC1_TCR    SNMM_HC1_TCR_CCITT
#define SNMM_HC1_TFA    SNMM_HC1_TFA_CCITT
#define SNMM_HC1_TCA    SNMM_HC1_TCA_CCITT
#define SNMM_HC1_RSP    SNMM_HC1_RSP_CCITT
#define SNMM_HC1_RSR    SNMM_HC1_RSR_CCITT
#define SNMM_HC1_RCP    SNMM_HC1_RCP_CCITT
#define SNMM_HC1_RCR    SNMM_HC1_RCR_CCITT
#define SNMM_HC1_LIN    SNMM_HC1_LIN_CCITT
#define SNMM_HC1_LUN    SNMM_HC1_LUN_CCITT
#define SNMM_HC1_LIA    SNMM_HC1_LIA_CCITT
#define SNMM_HC1_LUA    SNMM_HC1_LUA_CCITT
#define SNMM_HC1_LID    SNMM_HC1_LID_CCITT
#define SNMM_HC1_LFU    SNMM_HC1_LFU_CCITT
#define SNMM_HC1_LLI    SNMM_HC1_LLI_CCITT
#define SNMM_HC1_LRI    SNMM_HC1_LRI_CCITT
#define SNMM_HC1_DLC    SNMM_HC1_DLC_CCITT
#define SNMM_HC1_CSS    SNMM_HC1_CSS_CCITT
#define SNMM_HC1_CNS    SNMM_HC1_CNS_CCITT
#define SNMM_HC1_CNP    SNMM_HC1_CNP_CCITT
#define SNMM_HC1_RCT    SNMM_HC1_RCT_CCITT
#define SNMM_HC1_TFC    SNMM_HC1_TFC_CCITT
#define SNMM_HC1_TRA    SNMM_HC1_TRA_CCITT
#define SNMM_HC1_TRW    SNMM_HC1_TRW_CCITT
#define SNMM_HC1_UPU    SNMM_HC1_UPU_CCITT

#define SNMM_HC0_GET    SNMM_HC0_GET_CCITT
#define SNMM_HC0_SET    SNMM_HC0_SET_CCITT
#define SNMM_HC1_GET    SNMM_HC1_GET_CCITT
#define SNMM_HC1_SET    SNMM_HC1_SET_CCITT

#define SNMM_CHANGEOVER SNMM_CHANGEOVER_CCITT

#define SNMM_CHANGEOVER_GET_SLC     SNMM_CHANGEOVER_GET_SLC_CCITT
#define SNMM_CHANGEOVER_SET_SLC     SNMM_CHANGEOVER_SET_SLC_CCITT
#define SNMM_CHANGEOVER_GET_FSN     SNMM_CHANGEOVER_GET_FSN_CCITT
#define SNMM_CHANGEOVER_SET_FSN     SNMM_CHANGEOVER_SET_FSN_CCITT
#define SNMM_CHANGEOVER_GET_FSN_SAAL     SNMM_CHANGEOVER_GET_FSN_SAAL_CCITT
#define SNMM_CHANGEOVER_SET_FSN_SAAL     SNMM_CHANGEOVER_SET_FSN_SAAL_CCITT

#define SNMM_CHANGEBACK SNMM_CHANGEBACK_CCITT

#define SNMM_CHANGEBACK_GET_SLC     SNMM_CHANGEBACK_GET_SLC_CCITT
#define SNMM_CHANGEBACK_SET_SLC     SNMM_CHANGEBACK_SET_SLC_CCITT
#define SNMM_CHANGEBACK_GET_CODE    SNMM_CHANGEBACK_GET_CODE_CCITT
#define SNMM_CHANGEBACK_SET_CODE    SNMM_CHANGEBACK_SET_CODE_CCITT

#define SNMM_EMERG_CHANGEOVER       SNMM_EMERG_CHANGEOVER_CCITT

#define SNMM_EMERG_CHANGEOVER_GET_SLC   SNMM_EMERG_CHANGEOVER_GET_SLC_CCITT
#define SNMM_EMERG_CHANGEOVER_SET_SLC   SNMM_EMERG_CHANGEOVER_SET_SLC_CCITT

#define SNMM_TRANSFER_STATE   SNMM_TRANSFER_STATE_CCITT

#define SNMM_TRANSFER_STATE_GET_DEST  SNMM_TRANSFER_STATE_GET_DEST_CCITT
#define SNMM_TRANSFER_STATE_SET_DEST  SNMM_TRANSFER_STATE_SET_DEST_CCITT

#define SNMM_ROUTE_SET_TEST     SNMM_ROUTE_SET_TEST_CCITT

#define SNMM_ROUTE_SET_TEST_GET_DEST    SNMM_ROUTE_SET_TEST_GET_DEST_CCITT
#define SNMM_ROUTE_SET_TEST_SET_DEST    SNMM_ROUTE_SET_TEST_SET_DEST_CCITT

#define SNMM_INHIBIT    SNMM_INHIBIT_CCITT

#define SNMM_INHIBIT_GET_SLC    SNMM_INHIBIT_GET_SLC_CCITT
#define SNMM_INHIBIT_SET_SLC    SNMM_INHIBIT_SET_SLC_CCITT

#define SNMM_DATALINK_CONNECT   SNMM_DATALINK_CONNECT_CCITT

#define SNMM_DATALINK_CONNECT_GET_SLC   SNMM_DATALINK_CONNECT_GET_SLC_CCITT
#define SNMM_DATALINK_CONNECT_SET_SLC   SNMM_DATALINK_CONNECT_SET_SLC_CCITT
#define SNMM_DATALINK_CONNECT_GET_LINK  SNMM_DATALINK_CONNECT_GET_LINK_CCITT
#define SNMM_DATALINK_CONNECT_SET_LINK  SNMM_DATALINK_CONNECT_SET_LINK_CCITT

#define SNMM_DATALINK_CONN_ACK  SNMM_DATALINK_CONN_ACK_CCITT

#define SNMM_DATALINK_CONN_ACK_GET_SLC  SNMM_DATALINK_CONN_ACK_GET_SLC_CCITT
#define SNMM_DATALINK_CONN_ACK_SET_SLC  SNMM_DATALINK_CONN_ACK_SET_SLC_CCITT

#define SNMM_TRANSFER_CONTROL    SNMM_TRANSFER_CONTROL_CCITT

#define SNMM_TRANSFER_CONTROL_GET_DEST      SNMM_TRANSFER_CONTROL_GET_DEST_CCITT
#define SNMM_TRANSFER_CONTROL_SET_DEST      SNMM_TRANSFER_CONTROL_SET_DEST_CCITT
#define SNMM_TRANSFER_CONTROL_GET_STATUS    SNMM_TRANSFER_CONTROL_GET_STATUS_CCITT
#define SNMM_TRANSFER_CONTROL_SET_STATUS    SNMM_TRANSFER_CONTROL_SET_STATUS_CCITT

#define SNMM_USER_PART_UNAVAILABLE      SNMM_USER_PART_UNAVAILABLE_CCITT

#define SNMM_USER_PART_UNAVAIL_GET_DEST SNMM_USER_PART_UNAVAIL_GET_DEST_CCITT
#define SNMM_USER_PART_UNAVAIL_SET_DEST SNMM_USER_PART_UNAVAIL_SET_DEST_CCITT
#define SNMM_USER_PART_UNAVAIL_GET_USER SNMM_USER_PART_UNAVAIL_GET_USER_CCITT
#define SNMM_USER_PART_UNAVAIL_SET_USER SNMM_USER_PART_UNAVAIL_SET_USER_CCITT
#define SNMM_USER_PART_UNAVAIL_GET_CAUSE SNMM_USER_PART_UNAVAIL_GET_CAUSE_CCITT
#define SNMM_USER_PART_UNAVAIL_SET_CAUSE SNMM_USER_PART_UNAVAIL_SET_CAUSE_CCITT

#define SNMM_Encode     SNMM_Encode_CCITT
#define SNMM_Decode     SNMM_Decode_CCITT

#elif defined(ANSI) /***************************************************/

#define SNMM_HEADING_CODE_0_MASK    SNMM_HEADING_CODE_0_MASK_ANSI
#define SNMM_HEADING_CODE_1_MASK    SNMM_HEADING_CODE_1_MASK_ANSI

#define SNMM_HC0_SPARE  SNMM_HC0_SPARE_ANSI
#define SNMM_HC0_CHM    SNMM_HC0_CHM_ANSI
#define SNMM_HC0_ECM    SNMM_HC0_ECM_ANSI
#define SNMM_HC0_FCM    SNMM_HC0_FCM_ANSI
#define SNMM_HC0_TFM    SNMM_HC0_TFM_ANSI
#define SNMM_HC0_RSM    SNMM_HC0_RSM_ANSI
#define SNMM_HC0_MIM    SNMM_HC0_MIM_ANSI
#define SNMM_HC0_TRM    SNMM_HC0_TRM_ANSI
#define SNMM_HC0_DLM    SNMM_HC0_DLM_ANSI
#define SNMM_HC0_UFC    SNMM_HC0_UFC_ANSI

#define SNMM_HC1_COO    SNMM_HC1_COO_ANSI
#define SNMM_HC1_COA    SNMM_HC1_COA_ANSI
#define SNMM_HC1_XCO    SNMM_HC1_XCO_ANSI
#define SNMM_HC1_XCA    SNMM_HC1_XCA_ANSI
#define SNMM_HC1_CBD    SNMM_HC1_CBD_ANSI
#define SNMM_HC1_CBA    SNMM_HC1_CBA_ANSI
#define SNMM_HC1_ECO    SNMM_HC1_ECO_ANSI
#define SNMM_HC1_ECA    SNMM_HC1_ECA_ANSI
#define SNMM_HC1_TFP    SNMM_HC1_TFP_ANSI
#define SNMM_HC1_TCP    SNMM_HC1_TCP_ANSI
#define SNMM_HC1_TFR    SNMM_HC1_TFR_ANSI
#define SNMM_HC1_TCR    SNMM_HC1_TCR_ANSI
#define SNMM_HC1_TFA    SNMM_HC1_TFA_ANSI
#define SNMM_HC1_TCA    SNMM_HC1_TCA_ANSI
#define SNMM_HC1_RSP    SNMM_HC1_RSP_ANSI
#define SNMM_HC1_RSR    SNMM_HC1_RSR_ANSI
#define SNMM_HC1_RCP    SNMM_HC1_RCP_ANSI
#define SNMM_HC1_RCR    SNMM_HC1_RCR_ANSI
#define SNMM_HC1_LIN    SNMM_HC1_LIN_ANSI
#define SNMM_HC1_LUN    SNMM_HC1_LUN_ANSI
#define SNMM_HC1_LIA    SNMM_HC1_LIA_ANSI
#define SNMM_HC1_LUA    SNMM_HC1_LUA_ANSI
#define SNMM_HC1_LID    SNMM_HC1_LID_ANSI
#define SNMM_HC1_LFU    SNMM_HC1_LFU_ANSI
#define SNMM_HC1_LLI    SNMM_HC1_LLI_ANSI
#define SNMM_HC1_LRI    SNMM_HC1_LRI_ANSI
#define SNMM_HC1_DLC    SNMM_HC1_DLC_ANSI
#define SNMM_HC1_CSS    SNMM_HC1_CSS_ANSI
#define SNMM_HC1_CNS    SNMM_HC1_CNS_ANSI
#define SNMM_HC1_CNP    SNMM_HC1_CNP_ANSI
#define SNMM_HC1_RCT    SNMM_HC1_RCT_ANSI
#define SNMM_HC1_TFC    SNMM_HC1_TFC_ANSI
#define SNMM_HC1_TRA    SNMM_HC1_TRA_ANSI
#define SNMM_HC1_TRW    SNMM_HC1_TRW_ANSI
#define SNMM_HC1_UPU    SNMM_HC1_UPU_ANSI

#define SNMM_HC0_GET    SNMM_HC0_GET_ANSI
#define SNMM_HC0_SET    SNMM_HC0_SET_ANSI
#define SNMM_HC1_GET    SNMM_HC1_GET_ANSI
#define SNMM_HC1_SET    SNMM_HC1_SET_ANSI

#define SNMM_CHANGEOVER SNMM_CHANGEOVER_ANSI

#define SNMM_CHANGEOVER_GET_SLC     SNMM_CHANGEOVER_GET_SLC_ANSI
#define SNMM_CHANGEOVER_SET_SLC     SNMM_CHANGEOVER_SET_SLC_ANSI
#define SNMM_CHANGEOVER_GET_FSN     SNMM_CHANGEOVER_GET_FSN_ANSI
#define SNMM_CHANGEOVER_SET_FSN     SNMM_CHANGEOVER_SET_FSN_ANSI
#define SNMM_CHANGEOVER_GET_FSN_SAAL     SNMM_CHANGEOVER_GET_FSN_SAAL_ANSI
#define SNMM_CHANGEOVER_SET_FSN_SAAL     SNMM_CHANGEOVER_SET_FSN_SAAL_ANSI

#define SNMM_CHANGEBACK SNMM_CHANGEBACK_ANSI

#define SNMM_CHANGEBACK_GET_SLC     SNMM_CHANGEBACK_GET_SLC_ANSI
#define SNMM_CHANGEBACK_SET_SLC     SNMM_CHANGEBACK_SET_SLC_ANSI
#define SNMM_CHANGEBACK_GET_CODE    SNMM_CHANGEBACK_GET_CODE_ANSI
#define SNMM_CHANGEBACK_SET_CODE    SNMM_CHANGEBACK_SET_CODE_ANSI

#define SNMM_EMERG_CHANGEOVER       SNMM_EMERG_CHANGEOVER_ANSI

#define SNMM_EMERG_CHANGEOVER_GET_SLC   SNMM_EMERG_CHANGEOVER_GET_SLC_ANSI
#define SNMM_EMERG_CHANGEOVER_SET_SLC   SNMM_EMERG_CHANGEOVER_SET_SLC_ANSI

#define SNMM_TRANSFER_STATE   SNMM_TRANSFER_STATE_ANSI

#define SNMM_TRANSFER_STATE_GET_DEST  SNMM_TRANSFER_STATE_GET_DEST_ANSI
#define SNMM_TRANSFER_STATE_SET_DEST  SNMM_TRANSFER_STATE_SET_DEST_ANSI

#define SNMM_ROUTE_SET_TEST     SNMM_ROUTE_SET_TEST_ANSI

#define SNMM_ROUTE_SET_TEST_GET_DEST    SNMM_ROUTE_SET_TEST_GET_DEST_ANSI
#define SNMM_ROUTE_SET_TEST_SET_DEST    SNMM_ROUTE_SET_TEST_SET_DEST_ANSI

#define SNMM_INHIBIT    SNMM_INHIBIT_ANSI

#define SNMM_INHIBIT_GET_SLC    SNMM_INHIBIT_GET_SLC_ANSI
#define SNMM_INHIBIT_SET_SLC    SNMM_INHIBIT_SET_SLC_ANSI

#define SNMM_DATALINK_CONNECT   SNMM_DATALINK_CONNECT_ANSI

#define SNMM_DATALINK_CONNECT_GET_SLC   SNMM_DATALINK_CONNECT_GET_SLC_ANSI
#define SNMM_DATALINK_CONNECT_SET_SLC   SNMM_DATALINK_CONNECT_SET_SLC_ANSI
#define SNMM_DATALINK_CONNECT_GET_LINK  SNMM_DATALINK_CONNECT_GET_LINK_ANSI
#define SNMM_DATALINK_CONNECT_SET_LINK  SNMM_DATALINK_CONNECT_SET_LINK_ANSI

#define SNMM_DATALINK_CONN_ACK  SNMM_DATALINK_CONN_ACK_ANSI

#define SNMM_DATALINK_CONN_ACK_GET_SLC  SNMM_DATALINK_CONN_ACK_GET_SLC_ANSI
#define SNMM_DATALINK_CONN_ACK_SET_SLC  SNMM_DATALINK_CONN_ACK_SET_SLC_ANSI

#define SNMM_TRANSFER_CONTROL    SNMM_TRANSFER_CONTROL_ANSI

#define SNMM_TRANSFER_CONTROL_GET_DEST      SNMM_TRANSFER_CONTROL_GET_DEST_ANSI
#define SNMM_TRANSFER_CONTROL_SET_DEST      SNMM_TRANSFER_CONTROL_SET_DEST_ANSI
#define SNMM_TRANSFER_CONTROL_GET_STATUS    SNMM_TRANSFER_CONTROL_GET_STATUS_ANSI
#define SNMM_TRANSFER_CONTROL_SET_STATUS    SNMM_TRANSFER_CONTROL_SET_STATUS_ANSI

#define SNMM_USER_PART_UNAVAILABLE      SNMM_USER_PART_UNAVAILABLE_ANSI

#define SNMM_USER_PART_UNAVAIL_GET_DEST SNMM_USER_PART_UNAVAILABLE_GET_DEST_ANSI
#define SNMM_USER_PART_UNAVAIL_SET_DEST SNMM_USER_PART_UNAVAILABLE_SET_DEST_ANSI
#define SNMM_USER_PART_UNAVAIL_GET_USER SNMM_USER_PART_UNAVAILABLE_GET_USER_ANSI
#define SNMM_USER_PART_UNAVAIL_SET_USER SNMM_USER_PART_UNAVAILABLE_SET_USER_ANSI

#define SNMM_Encode     SNMM_Encode_ANSI
#define SNMM_Decode     SNMM_Decode_ANSI

#elif defined(PRC)

#define SNMM_HEADING_CODE_0_MASK    SNMM_HEADING_CODE_0_MASK_PRC
#define SNMM_HEADING_CODE_1_MASK    SNMM_HEADING_CODE_1_MASK_PRC

#define SNMM_HC0_SPARE  SNMM_HC0_SPARE_PRC
#define SNMM_HC0_CHM    SNMM_HC0_CHM_PRC
#define SNMM_HC0_ECM    SNMM_HC0_ECM_PRC
#define SNMM_HC0_FCM    SNMM_HC0_FCM_PRC
#define SNMM_HC0_TFM    SNMM_HC0_TFM_PRC
#define SNMM_HC0_RSM    SNMM_HC0_RSM_PRC
#define SNMM_HC0_MIM    SNMM_HC0_MIM_PRC
#define SNMM_HC0_TRM    SNMM_HC0_TRM_PRC
#define SNMM_HC0_DLM    SNMM_HC0_DLM_PRC
#define SNMM_HC0_UFC    SNMM_HC0_UFC_PRC

#define SNMM_HC1_COO    SNMM_HC1_COO_PRC
#define SNMM_HC1_COA    SNMM_HC1_COA_PRC
#define SNMM_HC1_XCO    SNMM_HC1_XCO_PRC
#define SNMM_HC1_XCA    SNMM_HC1_XCA_PRC
#define SNMM_HC1_CBD    SNMM_HC1_CBD_PRC
#define SNMM_HC1_CBA    SNMM_HC1_CBA_PRC
#define SNMM_HC1_ECO    SNMM_HC1_ECO_PRC
#define SNMM_HC1_ECA    SNMM_HC1_ECA_PRC
#define SNMM_HC1_TFP    SNMM_HC1_TFP_PRC
#define SNMM_HC1_TCP    SNMM_HC1_TCP_PRC
#define SNMM_HC1_TFR    SNMM_HC1_TFR_PRC
#define SNMM_HC1_TCR    SNMM_HC1_TCR_PRC
#define SNMM_HC1_TFA    SNMM_HC1_TFA_PRC
#define SNMM_HC1_TCA    SNMM_HC1_TCA_PRC
#define SNMM_HC1_RSP    SNMM_HC1_RSP_PRC
#define SNMM_HC1_RSR    SNMM_HC1_RSR_PRC
#define SNMM_HC1_RCP    SNMM_HC1_RCP_PRC
#define SNMM_HC1_RCR    SNMM_HC1_RCR_PRC
#define SNMM_HC1_LIN    SNMM_HC1_LIN_PRC
#define SNMM_HC1_LUN    SNMM_HC1_LUN_PRC
#define SNMM_HC1_LIA    SNMM_HC1_LIA_PRC
#define SNMM_HC1_LUA    SNMM_HC1_LUA_PRC
#define SNMM_HC1_LID    SNMM_HC1_LID_PRC
#define SNMM_HC1_LFU    SNMM_HC1_LFU_PRC
#define SNMM_HC1_LLI    SNMM_HC1_LLI_PRC
#define SNMM_HC1_LRI    SNMM_HC1_LRI_PRC
#define SNMM_HC1_DLC    SNMM_HC1_DLC_PRC
#define SNMM_HC1_CSS    SNMM_HC1_CSS_PRC
#define SNMM_HC1_CNS    SNMM_HC1_CNS_PRC
#define SNMM_HC1_CNP    SNMM_HC1_CNP_PRC
#define SNMM_HC1_RCT    SNMM_HC1_RCT_PRC
#define SNMM_HC1_TFC    SNMM_HC1_TFC_PRC
#define SNMM_HC1_TRA    SNMM_HC1_TRA_PRC
#define SNMM_HC1_TRW    SNMM_HC1_TRW_PRC
#define SNMM_HC1_UPU    SNMM_HC1_UPU_PRC

#define SNMM_HC0_GET    SNMM_HC0_GET_PRC
#define SNMM_HC0_SET    SNMM_HC0_SET_PRC
#define SNMM_HC1_GET    SNMM_HC1_GET_PRC
#define SNMM_HC1_SET    SNMM_HC1_SET_PRC

#define SNMM_CHANGEOVER SNMM_CHANGEOVER_PRC

#define SNMM_CHANGEOVER_GET_SLC     SNMM_CHANGEOVER_GET_SLC_PRC
#define SNMM_CHANGEOVER_SET_SLC     SNMM_CHANGEOVER_SET_SLC_PRC
#define SNMM_CHANGEOVER_GET_FSN     SNMM_CHANGEOVER_GET_FSN_PRC
#define SNMM_CHANGEOVER_SET_FSN     SNMM_CHANGEOVER_SET_FSN_PRC
#define SNMM_CHANGEOVER_GET_FSN_SAAL     SNMM_CHANGEOVER_GET_FSN_SAAL_PRC
#define SNMM_CHANGEOVER_SET_FSN_SAAL     SNMM_CHANGEOVER_SET_FSN_SAAL_PRC

#define SNMM_CHANGEBACK SNMM_CHANGEBACK_PRC

#define SNMM_CHANGEBACK_GET_SLC     SNMM_CHANGEBACK_GET_SLC_PRC
#define SNMM_CHANGEBACK_SET_SLC     SNMM_CHANGEBACK_SET_SLC_PRC
#define SNMM_CHANGEBACK_GET_CODE    SNMM_CHANGEBACK_GET_CODE_PRC
#define SNMM_CHANGEBACK_SET_CODE    SNMM_CHANGEBACK_SET_CODE_PRC

#define SNMM_EMERG_CHANGEOVER       SNMM_EMERG_CHANGEOVER_PRC

#define SNMM_EMERG_CHANGEOVER_GET_SLC   SNMM_EMERG_CHANGEOVER_GET_SLC_PRC
#define SNMM_EMERG_CHANGEOVER_SET_SLC   SNMM_EMERG_CHANGEOVER_SET_SLC_PRC

#define SNMM_TRANSFER_STATE   SNMM_TRANSFER_STATE_PRC

#define SNMM_TRANSFER_STATE_GET_DEST  SNMM_TRANSFER_STATE_GET_DEST_PRC
#define SNMM_TRANSFER_STATE_SET_DEST  SNMM_TRANSFER_STATE_SET_DEST_PRC

#define SNMM_ROUTE_SET_TEST     SNMM_ROUTE_SET_TEST_PRC

#define SNMM_ROUTE_SET_TEST_GET_DEST    SNMM_ROUTE_SET_TEST_GET_DEST_PRC
#define SNMM_ROUTE_SET_TEST_SET_DEST    SNMM_ROUTE_SET_TEST_SET_DEST_PRC

#define SNMM_INHIBIT    SNMM_INHIBIT_PRC

#define SNMM_INHIBIT_GET_SLC    SNMM_INHIBIT_GET_SLC_PRC
#define SNMM_INHIBIT_SET_SLC    SNMM_INHIBIT_SET_SLC_PRC

#define SNMM_DATALINK_CONNECT   SNMM_DATALINK_CONNECT_PRC

#define SNMM_DATALINK_CONNECT_GET_SLC   SNMM_DATALINK_CONNECT_GET_SLC_PRC
#define SNMM_DATALINK_CONNECT_SET_SLC   SNMM_DATALINK_CONNECT_SET_SLC_PRC
#define SNMM_DATALINK_CONNECT_GET_LINK  SNMM_DATALINK_CONNECT_GET_LINK_PRC
#define SNMM_DATALINK_CONNECT_SET_LINK  SNMM_DATALINK_CONNECT_SET_LINK_PRC

#define SNMM_DATALINK_CONN_ACK  SNMM_DATALINK_CONN_ACK_PRC

#define SNMM_DATALINK_CONN_ACK_GET_SLC  SNMM_DATALINK_CONN_ACK_GET_SLC_PRC
#define SNMM_DATALINK_CONN_ACK_SET_SLC  SNMM_DATALINK_CONN_ACK_SET_SLC_PRC

#define SNMM_TRANSFER_CONTROL    SNMM_TRANSFER_CONTROL_PRC

#define SNMM_TRANSFER_CONTROL_GET_DEST      SNMM_TRANSFER_CONTROL_GET_DEST_PRC
#define SNMM_TRANSFER_CONTROL_SET_DEST      SNMM_TRANSFER_CONTROL_SET_DEST_PRC
#define SNMM_TRANSFER_CONTROL_GET_STATUS    SNMM_TRANSFER_CONTROL_GET_STATUS_PRC
#define SNMM_TRANSFER_CONTROL_SET_STATUS    SNMM_TRANSFER_CONTROL_SET_STATUS_PRC

#define SNMM_USER_PART_UNAVAILABLE      SNMM_USER_PART_UNAVAILABLE_PRC

#define SNMM_USER_PART_UNAVAIL_GET_DEST SNMM_USER_PART_UNAVAIL_GET_DEST_PRC
#define SNMM_USER_PART_UNAVAIL_SET_DEST SNMM_USER_PART_UNAVAIL_SET_DEST_PRC
#define SNMM_USER_PART_UNAVAIL_GET_USER SNMM_USER_PART_UNAVAIL_GET_USER_PRC
#define SNMM_USER_PART_UNAVAIL_SET_USER SNMM_USER_PART_UNAVAIL_SET_USER_PRC
#define SNMM_USER_PART_UNAVAIL_GET_CAUSE SNMM_USER_PART_UNAVAIL_GET_CAUSE_PRC
#define SNMM_USER_PART_UNAVAIL_SET_CAUSE SNMM_USER_PART_UNAVAIL_SET_CAUSE_PRC

#define SNMM_Encode     SNMM_Encode_PRC
#define SNMM_Decode     SNMM_Decode_PRC

#elif defined(TTC)

#define SNMM_HEADING_CODE_0_MASK    SNMM_HEADING_CODE_0_MASK_TTC
#define SNMM_HEADING_CODE_1_MASK    SNMM_HEADING_CODE_1_MASK_TTC

#define SNMM_HC0_SPARE  SNMM_HC0_SPARE_TTC
#define SNMM_HC0_CHM    SNMM_HC0_CHM_TTC
#define SNMM_HC0_ECM    SNMM_HC0_ECM_TTC
#define SNMM_HC0_FCM    SNMM_HC0_FCM_TTC
#define SNMM_HC0_TFM    SNMM_HC0_TFM_TTC
#define SNMM_HC0_RSM    SNMM_HC0_RSM_TTC
#define SNMM_HC0_MIM    SNMM_HC0_MIM_TTC
#define SNMM_HC0_TRM    SNMM_HC0_TRM_TTC
#define SNMM_HC0_DLM    SNMM_HC0_DLM_TTC
#define SNMM_HC0_UFC    SNMM_HC0_UFC_TTC

#define SNMM_HC1_COO    SNMM_HC1_COO_TTC
#define SNMM_HC1_COA    SNMM_HC1_COA_TTC
#define SNMM_HC1_XCO    SNMM_HC1_XCO_TTC
#define SNMM_HC1_XCA    SNMM_HC1_XCA_TTC
#define SNMM_HC1_CBD    SNMM_HC1_CBD_TTC
#define SNMM_HC1_CBA    SNMM_HC1_CBA_TTC
#define SNMM_HC1_ECO    SNMM_HC1_ECO_TTC
#define SNMM_HC1_ECA    SNMM_HC1_ECA_TTC
#define SNMM_HC1_TFP    SNMM_HC1_TFP_TTC
#define SNMM_HC1_TCP    SNMM_HC1_TCP_TTC
#define SNMM_HC1_TFR    SNMM_HC1_TFR_TTC
#define SNMM_HC1_TCR    SNMM_HC1_TCR_TTC
#define SNMM_HC1_TFA    SNMM_HC1_TFA_TTC
#define SNMM_HC1_TCA    SNMM_HC1_TCA_TTC
#define SNMM_HC1_RSP    SNMM_HC1_RSP_TTC
#define SNMM_HC1_RSR    SNMM_HC1_RSR_TTC
#define SNMM_HC1_RCP    SNMM_HC1_RCP_TTC
#define SNMM_HC1_RCR    SNMM_HC1_RCR_TTC
#define SNMM_HC1_LIN    SNMM_HC1_LIN_TTC
#define SNMM_HC1_LUN    SNMM_HC1_LUN_TTC
#define SNMM_HC1_LIA    SNMM_HC1_LIA_TTC
#define SNMM_HC1_LUA    SNMM_HC1_LUA_TTC
#define SNMM_HC1_LID    SNMM_HC1_LID_TTC
#define SNMM_HC1_LFU    SNMM_HC1_LFU_TTC
#define SNMM_HC1_LLI    SNMM_HC1_LLI_TTC
#define SNMM_HC1_LRI    SNMM_HC1_LRI_TTC
#define SNMM_HC1_DLC    SNMM_HC1_DLC_TTC
#define SNMM_HC1_CSS    SNMM_HC1_CSS_TTC
#define SNMM_HC1_CNS    SNMM_HC1_CNS_TTC
#define SNMM_HC1_CNP    SNMM_HC1_CNP_TTC
#define SNMM_HC1_RCT    SNMM_HC1_RCT_TTC
#define SNMM_HC1_TFC    SNMM_HC1_TFC_TTC
#define SNMM_HC1_TRA    SNMM_HC1_TRA_TTC
#define SNMM_HC1_TRW    SNMM_HC1_TRW_TTC
#define SNMM_HC1_UPU    SNMM_HC1_UPU_TTC

#define SNMM_HC0_GET    SNMM_HC0_GET_TTC
#define SNMM_HC0_SET    SNMM_HC0_SET_TTC
#define SNMM_HC1_GET    SNMM_HC1_GET_TTC
#define SNMM_HC1_SET    SNMM_HC1_SET_TTC

#define SNMM_CHANGEOVER SNMM_CHANGEOVER_TTC

#define SNMM_CHANGEOVER_GET_SLC     SNMM_CHANGEOVER_GET_SLC_TTC
#define SNMM_CHANGEOVER_SET_SLC     SNMM_CHANGEOVER_SET_SLC_TTC
#define SNMM_CHANGEOVER_GET_FSN     SNMM_CHANGEOVER_GET_FSN_TTC
#define SNMM_CHANGEOVER_SET_FSN     SNMM_CHANGEOVER_SET_FSN_TTC
#define SNMM_CHANGEOVER_GET_FSN_SAAL     SNMM_CHANGEOVER_GET_FSN_SAAL_TTC
#define SNMM_CHANGEOVER_SET_FSN_SAAL     SNMM_CHANGEOVER_SET_FSN_SAAL_TTC

#define SNMM_CHANGEBACK SNMM_CHANGEBACK_TTC

#define SNMM_CHANGEBACK_GET_SLC     SNMM_CHANGEBACK_GET_SLC_TTC
#define SNMM_CHANGEBACK_SET_SLC     SNMM_CHANGEBACK_SET_SLC_TTC
#define SNMM_CHANGEBACK_GET_CODE    SNMM_CHANGEBACK_GET_CODE_TTC
#define SNMM_CHANGEBACK_SET_CODE    SNMM_CHANGEBACK_SET_CODE_TTC

#define SNMM_EMERG_CHANGEOVER       SNMM_EMERG_CHANGEOVER_TTC

#define SNMM_EMERG_CHANGEOVER_GET_SLC   SNMM_EMERG_CHANGEOVER_GET_SLC_TTC
#define SNMM_EMERG_CHANGEOVER_SET_SLC   SNMM_EMERG_CHANGEOVER_SET_SLC_TTC

#define SNMM_TRANSFER_STATE   SNMM_TRANSFER_STATE_TTC

#define SNMM_TRANSFER_STATE_GET_DEST  SNMM_TRANSFER_STATE_GET_DEST_TTC
#define SNMM_TRANSFER_STATE_SET_DEST  SNMM_TRANSFER_STATE_SET_DEST_TTC

#define SNMM_ROUTE_SET_TEST     SNMM_ROUTE_SET_TEST_TTC

#define SNMM_ROUTE_SET_TEST_GET_DEST    SNMM_ROUTE_SET_TEST_GET_DEST_TTC
#define SNMM_ROUTE_SET_TEST_SET_DEST    SNMM_ROUTE_SET_TEST_SET_DEST_TTC

#define SNMM_INHIBIT    SNMM_INHIBIT_TTC

#define SNMM_INHIBIT_GET_SLC    SNMM_INHIBIT_GET_SLC_TTC
#define SNMM_INHIBIT_SET_SLC    SNMM_INHIBIT_SET_SLC_TTC

#define SNMM_DATALINK_CONNECT   SNMM_DATALINK_CONNECT_TTC

#define SNMM_DATALINK_CONNECT_GET_SLC   SNMM_DATALINK_CONNECT_GET_SLC_TTC
#define SNMM_DATALINK_CONNECT_SET_SLC   SNMM_DATALINK_CONNECT_SET_SLC_TTC
#define SNMM_DATALINK_CONNECT_GET_LINK  SNMM_DATALINK_CONNECT_GET_LINK_TTC
#define SNMM_DATALINK_CONNECT_SET_LINK  SNMM_DATALINK_CONNECT_SET_LINK_TTC

#define SNMM_DATALINK_CONN_ACK  SNMM_DATALINK_CONN_ACK_TTC

#define SNMM_DATALINK_CONN_ACK_GET_SLC  SNMM_DATALINK_CONN_ACK_GET_SLC_TTC
#define SNMM_DATALINK_CONN_ACK_SET_SLC  SNMM_DATALINK_CONN_ACK_SET_SLC_TTC

#define SNMM_TRANSFER_CONTROL    SNMM_TRANSFER_CONTROL_TTC

#define SNMM_TRANSFER_CONTROL_GET_DEST      SNMM_TRANSFER_CONTROL_GET_DEST_TTC
#define SNMM_TRANSFER_CONTROL_SET_DEST      SNMM_TRANSFER_CONTROL_SET_DEST_TTC
#define SNMM_TRANSFER_CONTROL_GET_STATUS    SNMM_TRANSFER_CONTROL_GET_STATUS_TTC
#define SNMM_TRANSFER_CONTROL_SET_STATUS    SNMM_TRANSFER_CONTROL_SET_STATUS_TTC

#define SNMM_USER_PART_UNAVAILABLE      SNMM_USER_PART_UNAVAILABLE_TTC

#define SNMM_USER_PART_UNAVAIL_GET_DEST SNMM_USER_PART_UNAVAIL_GET_DEST_TTC
#define SNMM_USER_PART_UNAVAIL_SET_DEST SNMM_USER_PART_UNAVAIL_SET_DEST_TTC
#define SNMM_USER_PART_UNAVAIL_GET_USER SNMM_USER_PART_UNAVAIL_GET_USER_TTC
#define SNMM_USER_PART_UNAVAIL_SET_USER SNMM_USER_PART_UNAVAIL_SET_USER_TTC
#define SNMM_USER_PART_UNAVAIL_GET_CAUSE SNMM_USER_PART_UNAVAIL_GET_CAUSE_TTC
#define SNMM_USER_PART_UNAVAIL_SET_CAUSE SNMM_USER_PART_UNAVAIL_SET_CAUSE_TTC

#define SNMM_Encode     SNMM_Encode_TTC
#define SNMM_Decode     SNMM_Decode_TTC


#else
#error "Protocol family not defined."
#endif

#endif /* _ITS_SNMM_SN_H_ */

