/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.intellinet.diameter.mag.node;

import com.intellinet.diameter.mag.analysis.*;

public final class TPxy extends Token
{
    public TPxy()
    {
        super.setText("PXY");
    }

    public TPxy(int line, int pos)
    {
        super.setText("PXY");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TPxy(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPxy(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TPxy text.");
    }
}
