/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.intellinet.diameter.mag.node;

import com.intellinet.diameter.mag.analysis.*;

public final class TQosFilterRule extends Token
{
    public TQosFilterRule()
    {
        super.setText("QoSFilterRule");
    }

    public TQosFilterRule(int line, int pos)
    {
        super.setText("QoSFilterRule");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TQosFilterRule(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTQosFilterRule(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TQosFilterRule text.");
    }
}
