#!/bin/sh
########################################################################
#
# Copyright 2006 IntelliNet Technologies, Inc. All Rights Reserved.
#          Manufactured in the United States of America.
#   1990 W. New Haven Ste. 312, Melbourne, Florida, 32904 U.S.A.
#
########################################################################

ISS7_CONFIG_DIR=/opt/IntelliNet/IDS/config/
export ISS7_CONFIG_DIR

case "$1" in
'start')
         if [ -x /opt/IntelliNet/IDS/bin/DIAMon ]
         then
            /opt/IntelliNet/IDS/bin/DIAMon
         fi
         exit 0
         ;;

'stop')
         if [ -x /opt/IntelliNet/scripts/stopdia ]
         then
            /opt/IntelliNet/scripts/stopdia
         fi
         exit 0
         ;;
 
*)
        echo "Usage: $0 { start | stop }"
        exit 1
        ;;
esac
