include ../Makefile.inc

BLOCKS_AR := libblocks.a
BLOCKS_OFILES := Logger.o Exception.o Allocator.o Sync.o Component.o \
                 Socket.o Dispatcher.o Signal.o SockEvent.o Timer.o Tipc.o \
                 MemPool.o PluginObj.o Thread.o Statistics.o SctpSock.o \
				 RandomNumber.o

TARGETS_AR := BLOCKS

include ../Makefile.rules

