############################################################################
#                                                                          #
#     Copyright 2006 IntelliNet Technologies, Inc. All Rights Reserved.    #
#             Manufactured in the United States of America.                #
#       1990 W. New Haven Ste. 312, Melbourne, Florida, 32904 U.S.A.       #
#                                                                          #
#   This product and related documentation is protected by copyright and   #
#   distributed under licenses restricting its use, copying, distribution  #
#   and decompilation.  No part of this product or related documentation   #
#   may be reproduced in any form by any means without prior written       #
#   authorization of IntelliNet Technologies and its licensors, if any.    #
#                                                                          #
#   RESTRICTED RIGHTS LEGEND:  Use, duplication, or disclosure by the      #
#   government is subject to restrictions as set forth in subparagraph     #
#   (c)(1)(ii) of the Rights in Technical Data and Computer Software       #
#   clause at DFARS 252.227-7013 and FAR 52.227-19.                        #
#                                                                          #
############################################################################
#                                                                          #
# CONTRACT: INTERNAL                                                       #
############################################################################
# FILE: Makefile                                                            
# LOG: $Log: Makefile,v $
# LOG: Revision 1.1.2.1  2013/02/08 10:52:30  jvikas
# LOG: Diameter Simulator Changes for IWF
# LOG:
# LOG: Revision 1.1.2.1  2013/01/28 11:31:38  pramana
# LOG: Initial check-in for simulator code
# LOG:
# LOG: Revision 1.1.2.1  2012/07/09 08:53:44  pramana
# LOG: New test code added for S6a, S13 for Release 10 support (Bug 48).
# LOG:
# LOG: Revision 1.1  2008/08/19 06:58:33  sureshj
# LOG: Baseline demo application for s6a interface.
# LOG:								   
# ID: $Id: Makefile,v 1.1.2.1 2013/02/08 10:52:30 jvikas Exp $							   
############################################################################
#
# components under this project
#
.PHONY: all clean realclean test

all :
	make -f Makefile.stat ; 
	#make -f Makefile.dist ; \

clean:
	make clean -f Makefile.stat ; \
	#make clean -f Makefile.dist ; \

