############################################################################
#                                                                          #
#     Copyright 2011 IntelliNet Technologies, Inc. All Rights Reserved.    #
#             Manufactured in the United States of America.                #
#       1990 W. New Haven Ste. 312, Melbourne, Florida, 32904 U.S.A.       #
#                                                                          #
#   This product and related documentation is protected by copyright and   #
#   distributed under licenses restricting its use, copying, distribution  #
#   and decompilation.  No part of this product or related documentation   #
#   may be reproduced in any form by any means without prior written       #
#   authorization of IntelliNet Technologies and its licensors, if any.    #
#                                                                          #
#   RESTRICTED RIGHTS LEGEND:  Use, duplication, or disclosure by the      #
#   government is subject to restrictions as set forth in subparagraph     #
#   (c)(1)(ii) of the Rights in Technical Data and Computer Software       #
#   clause at DFARS 252.227-7013 and FAR 52.227-19.                        #
#                                                                          #
############################################################################
#                                                                          #
# CONTRACT: INTERNAL                                                       #
#                                                                          #
# FILE: Makefile                                                           #
#                                                                          #
############################################################################
#                                                                          #
# ID: $Id: Makefile,v 1.1.4.2 2014/02/12 07:49:37 millayaraja Exp $
#
# LOG: $Log: Makefile,v $
# LOG: Revision 1.1.4.2  2014/02/12 07:49:37  millayaraja
# LOG: new testapp for IWF performance
# LOG:
# LOG: Revision 1.1.2.1  2013/07/03 06:49:20  jkchaitanya
# LOG:  changes for ro rel 10 make file
# LOG:
# LOG: Revision 1.1.2.1  2012/07/09 06:00:13  pramana
# LOG: Added to support release 10 (Bug 49).
# LOG:
# LOG: Revision 1.1  2011/03/10 09:27:34  vkumara
# LOG: Sample Demo for Gy Interface
# LOG:
# LOG:
#
############################################################################
#ident "$Id: Makefile,v 1.1.4.2 2014/02/12 07:49:37 millayaraja Exp $"

#
# components under this project
#
.PHONY: all clean realclean test

all :
	make -f Makefile.stat ; \
	#make -f Makefile.dist ; \

clean:
	make clean -f Makefile.stat ; \
	#make clean -f Makefile.dist ; \

