//
// Generated by IntelliAsnCC ASN.1 compiler (C, C++, Java).
//
// Do not edit!
//
//
//
// (C) 2000, 2001 IntelliNet Technologies Inc. All Rights Reserved.
//
//


#if !defined(_INAP_CS2_EVENT_TYPE_BCUSM_H_)
#define _INAP_CS2_EVENT_TYPE_BCUSM_H_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

#include <Asn.h>
#include <AsnObject.h>
#include <AsnDescObject.h>
#include <AsnError.h>

#include <AsnEnumerated.h>



namespace inap_cs2 {



class EventTypeBCUSM : public its::AsnEnumerated
{
public:

    EventTypeBCUSM() : its::AsnEnumerated(false)
    {
        Initialize();
    }

    EventTypeBCUSM(long value) : its::AsnEnumerated(value, false)
    {
        Initialize();
    }

    EventTypeBCUSM(its::Octets& octets) : its::AsnEnumerated(false)
    {
        Initialize();
        Decode(octets);
    }

    EventTypeBCUSM(const EventTypeBCUSM& rhs) : its::AsnEnumerated(rhs)
    {
        // Nothing to do.
    }

    EventTypeBCUSM(its::AsnDescObject* description) : its::AsnEnumerated(description)
    {
        // Nothing to do.
    }

    EventTypeBCUSM(its::AsnDescObject* description, long value) : its::AsnEnumerated(description, value)
    {
        // Nothing to do.
    }

protected:

    void Initialize()
    {
        _description = GetStaticDescription();
    }

public:

    static its::AsnDescObject* GetStaticDescription();

public:

    virtual ~EventTypeBCUSM()
    {
        // Nothing to do.
    }

    virtual its::AsnObject* Clone() const
    {
        return new EventTypeBCUSM(*this);
    }

    virtual std::string GetName() const
    { return "EventTypeBCUSM"; }

    virtual long Get(const std::string& valueName) const;

    virtual std::string Get(long value) const;

    virtual std::string GetExt(long value) const;

    enum {
        EVENT_TYPE_BCUSM_COMPONENT_RECEIVED = 127,
        EVENT_TYPE_BCUSM_ASSOCIATION_RELEASE_REQUESTED = 126

    };

    void SetComponentReceived()
    { _value = 127; }

    bool IsComponentReceived() const
    { return _value == 127; }

    void SetAssociationReleaseRequested()
    { _value = 126; }

    bool IsAssociationReleaseRequested() const
    { return _value == 126; }

};



} // namespace.

#endif    // !defined(_INAP_CS2_EVENT_TYPE_BCUSM_H_)

