//
// Generated by IntelliAsnCC ASN.1 compiler (C, C++, Java).
//
// Do not edit!
//
//
//
// (C) 2000, 2001 IntelliNet Technologies Inc. All Rights Reserved.
//
//


#if !defined(_INAP_CS2_INITIATE_CALL_ATTEMPT_ARG_H_)
#define _INAP_CS2_INITIATE_CALL_ATTEMPT_ARG_H_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

#include <Asn.h>
#include <AsnObject.h>
#include <AsnDescObject.h>
#include <AsnError.h>

#include <AsnSequence.h>
#include <AsnSequenceOf.h>
#include <AsnOctetString.h>
#include <AsnChoice.h>
#include <AsnInteger.h>

#include <inap_cs2_destination_routing_address.h>
#include <inap_cs2_alerting_pattern.h>
#include <inap_cs2_isdn_access_related_information.h>
#include <inap_cs2_travelling_class_mark.h>
#include <inap_cs2_extension_field.h>
#include <inap_cs2_service_interaction_indicators.h>
#include <inap_cs2_calling_party_number.h>
#include <inap_cs2_leg_id.h>
#include <inap_cs2_call_segment_id.h>
#include <inap_cs2_in_service_compatibility_response.h>
#include <inap_cs2_service_interaction_indicators_two.h>



namespace inap_cs2 {



class InitiateCallAttemptArg : public its::AsnSequence
{
public:


////////// Begin Nested Class(es) //////////



    class Extensions : public its::AsnSequenceOf
    {
    public:


    ////////// Begin Nested Class //////////


            typedef inap_cs2::ExtensionField ExtensionField;


    ////////// End Nested Class //////////

        Extensions() : its::AsnSequenceOf(false)
        {
            Initialize();
        }

        Extensions(its::Octets& octets) : its::AsnSequenceOf(false)
        {
            Initialize();
            Decode(octets);
        }

        Extensions(const Extensions& rhs) : its::AsnSequenceOf(rhs)
        {
            // Nothing to do.
        }

        Extensions(its::AsnDescObject* description) : its::AsnSequenceOf(description)
        {
            // Nothing to do.
        }

    protected:

        void Initialize()
        {
            _description = GetStaticDescription();
        }

    public:

        static its::AsnDescObject* GetStaticDescription();

        static its::AsnDescObject* GetExtensionFieldStaticDescription();

    public:

        virtual ~Extensions()
        {
            // Nothing to do.
        }

        virtual its::AsnObject* Clone() const
        {
            return new Extensions(*this);
        }

        virtual std::string GetName() const
        { return "Extensions"; }

        void AddElement(ExtensionField* element)
        {
            ITS_REQUIRE(element != NULL);
            element->AsnObject::SetDescription(GetExtensionFieldStaticDescription());
            AsnSequenceOf::AddElement(element);
        }

        void AddElement(const ExtensionField& element)
        {
            its::AsnObject& asnObject = const_cast<ExtensionField&>(element);
            asnObject.SetDescription(GetExtensionFieldStaticDescription());
            AsnSequenceOf::AddElement(element);
        }

        const ExtensionField& ElementAt(int index) const
        {
            return static_cast<const ExtensionField&> (AsnSequenceOf::ElementAt(index));
        }

    };


        typedef inap_cs2::DestinationRoutingAddress DestinationRoutingAddress;


        typedef inap_cs2::AlertingPattern AlertingPattern;


        typedef inap_cs2::ISDNAccessRelatedInformation ISDNAccessRelatedInformation;


        typedef inap_cs2::TravellingClassMark TravellingClassMark;


        typedef inap_cs2::ServiceInteractionIndicators ServiceInteractionIndicators;


        typedef inap_cs2::CallingPartyNumber CallingPartyNumber;


        typedef inap_cs2::LegID LegID;


        typedef inap_cs2::CallSegmentID CallSegmentID;


        typedef inap_cs2::INServiceCompatibilityResponse INServiceCompatibilityResponse;


        typedef inap_cs2::ServiceInteractionIndicatorsTwo ServiceInteractionIndicatorsTwo;


////////// End Nested Class(es) //////////

    InitiateCallAttemptArg() : its::AsnSequence(11, false)
    {
        Initialize();
    }

    InitiateCallAttemptArg(its::Octets& octets) : its::AsnSequence(11, false)
    {
        Initialize();
        Decode(octets);
    }

    InitiateCallAttemptArg(const InitiateCallAttemptArg& rhs) : its::AsnSequence(rhs)
    {
        // Nothing to do.
    }

    InitiateCallAttemptArg(its::AsnDescObject* description) : its::AsnSequence(11, description)
    {
        // Nothing to do.
    }

protected:

    void Initialize()
    {
        _description = GetStaticDescription();
    }

public:

    static its::AsnDescObject* GetStaticDescription();

    static its::AsnDescObject* GetDestinationRoutingAddressStaticDescription();
    static its::AsnDescObject* GetAlertingPatternStaticDescription();
    static its::AsnDescObject* GetISDNAccessRelatedInformationStaticDescription();
    static its::AsnDescObject* GetTravellingClassMarkStaticDescription();
    static its::AsnDescObject* GetExtensionsStaticDescription();
    static its::AsnDescObject* GetServiceInteractionIndicatorsStaticDescription();
    static its::AsnDescObject* GetCallingPartyNumberStaticDescription();
    static its::AsnDescObject* GetLegToBeCreatedStaticDescription();
    static its::AsnDescObject* GetNewCallSegmentStaticDescription();
    static its::AsnDescObject* GetINServiceCompatibilityResponseStaticDescription();
    static its::AsnDescObject* GetServiceInteractionIndicatorsTwoStaticDescription();

public:

    virtual ~InitiateCallAttemptArg()
    {
        // Nothing to do.
    }

    virtual its::AsnObject* Clone() const
    {
        return new InitiateCallAttemptArg(*this);
    }

    virtual std::string GetName() const
    { return "InitiateCallAttemptArg"; }

    void SetDestinationRoutingAddress(DestinationRoutingAddress* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetDestinationRoutingAddressStaticDescription());
        AddElement(0, element);
    }

    void SetDestinationRoutingAddress(const DestinationRoutingAddress& element)
    {
        its::AsnObject& asnObject = const_cast<DestinationRoutingAddress&>(element);
        asnObject.SetDescription(GetDestinationRoutingAddressStaticDescription());
        AddElement(0, element);
    }

    const DestinationRoutingAddress& GetDestinationRoutingAddress() const
    {
        return static_cast<const DestinationRoutingAddress&> (ElementAt(0));
    }

    void SetAlertingPattern(AlertingPattern* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetAlertingPatternStaticDescription());
        AddElement(1, element);
    }

    void SetAlertingPattern(const AlertingPattern& element)
    {
        its::AsnObject& asnObject = const_cast<AlertingPattern&>(element);
        asnObject.SetDescription(GetAlertingPatternStaticDescription());
        AddElement(1, element);
    }

    bool OptionAlertingPattern() const
    {
        return Contains(1);
    }

    const AlertingPattern& GetAlertingPattern() const
    {
        ITS_REQUIRE(OptionAlertingPattern());
        return static_cast<const AlertingPattern&> (ElementAt(1));
    }

    void SetISDNAccessRelatedInformation(ISDNAccessRelatedInformation* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetISDNAccessRelatedInformationStaticDescription());
        AddElement(2, element);
    }

    void SetISDNAccessRelatedInformation(const ISDNAccessRelatedInformation& element)
    {
        its::AsnObject& asnObject = const_cast<ISDNAccessRelatedInformation&>(element);
        asnObject.SetDescription(GetISDNAccessRelatedInformationStaticDescription());
        AddElement(2, element);
    }

    bool OptionISDNAccessRelatedInformation() const
    {
        return Contains(2);
    }

    const ISDNAccessRelatedInformation& GetISDNAccessRelatedInformation() const
    {
        ITS_REQUIRE(OptionISDNAccessRelatedInformation());
        return static_cast<const ISDNAccessRelatedInformation&> (ElementAt(2));
    }

    void SetTravellingClassMark(TravellingClassMark* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetTravellingClassMarkStaticDescription());
        AddElement(3, element);
    }

    void SetTravellingClassMark(const TravellingClassMark& element)
    {
        its::AsnObject& asnObject = const_cast<TravellingClassMark&>(element);
        asnObject.SetDescription(GetTravellingClassMarkStaticDescription());
        AddElement(3, element);
    }

    bool OptionTravellingClassMark() const
    {
        return Contains(3);
    }

    const TravellingClassMark& GetTravellingClassMark() const
    {
        ITS_REQUIRE(OptionTravellingClassMark());
        return static_cast<const TravellingClassMark&> (ElementAt(3));
    }

    void SetExtensions(Extensions* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetExtensionsStaticDescription());
        AddElement(4, element);
    }

    void SetExtensions(const Extensions& element)
    {
        its::AsnObject& asnObject = const_cast<Extensions&>(element);
        asnObject.SetDescription(GetExtensionsStaticDescription());
        AddElement(4, element);
    }

    bool OptionExtensions() const
    {
        return Contains(4);
    }

    const Extensions& GetExtensions() const
    {
        ITS_REQUIRE(OptionExtensions());
        return static_cast<const Extensions&> (ElementAt(4));
    }

    void SetServiceInteractionIndicators(ServiceInteractionIndicators* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetServiceInteractionIndicatorsStaticDescription());
        AddElement(5, element);
    }

    void SetServiceInteractionIndicators(const ServiceInteractionIndicators& element)
    {
        its::AsnObject& asnObject = const_cast<ServiceInteractionIndicators&>(element);
        asnObject.SetDescription(GetServiceInteractionIndicatorsStaticDescription());
        AddElement(5, element);
    }

    bool OptionServiceInteractionIndicators() const
    {
        return Contains(5);
    }

    const ServiceInteractionIndicators& GetServiceInteractionIndicators() const
    {
        ITS_REQUIRE(OptionServiceInteractionIndicators());
        return static_cast<const ServiceInteractionIndicators&> (ElementAt(5));
    }

    void SetCallingPartyNumber(CallingPartyNumber* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetCallingPartyNumberStaticDescription());
        AddElement(6, element);
    }

    void SetCallingPartyNumber(const CallingPartyNumber& element)
    {
        its::AsnObject& asnObject = const_cast<CallingPartyNumber&>(element);
        asnObject.SetDescription(GetCallingPartyNumberStaticDescription());
        AddElement(6, element);
    }

    bool OptionCallingPartyNumber() const
    {
        return Contains(6);
    }

    const CallingPartyNumber& GetCallingPartyNumber() const
    {
        ITS_REQUIRE(OptionCallingPartyNumber());
        return static_cast<const CallingPartyNumber&> (ElementAt(6));
    }

    void SetLegToBeCreated(LegID* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetLegToBeCreatedStaticDescription());
        AddElement(7, element);
    }

    void SetLegToBeCreated(const LegID& element)
    {
        its::AsnObject& asnObject = const_cast<LegID&>(element);
        asnObject.SetDescription(GetLegToBeCreatedStaticDescription());
        AddElement(7, element);
    }

    const LegID& GetLegToBeCreated() const
    {
        return static_cast<const LegID&> (ElementAt(7));
    }

    void SetNewCallSegment(CallSegmentID* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetNewCallSegmentStaticDescription());
        AddElement(8, element);
    }

    void SetNewCallSegment(const CallSegmentID& element)
    {
        its::AsnObject& asnObject = const_cast<CallSegmentID&>(element);
        asnObject.SetDescription(GetNewCallSegmentStaticDescription());
        AddElement(8, element);
    }

    const CallSegmentID& GetNewCallSegment() const
    {
        return static_cast<const CallSegmentID&> (ElementAt(8));
    }

    void SetINServiceCompatibilityResponse(INServiceCompatibilityResponse* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetINServiceCompatibilityResponseStaticDescription());
        AddElement(9, element);
    }

    void SetINServiceCompatibilityResponse(const INServiceCompatibilityResponse& element)
    {
        its::AsnObject& asnObject = const_cast<INServiceCompatibilityResponse&>(element);
        asnObject.SetDescription(GetINServiceCompatibilityResponseStaticDescription());
        AddElement(9, element);
    }

    bool OptionINServiceCompatibilityResponse() const
    {
        return Contains(9);
    }

    const INServiceCompatibilityResponse& GetINServiceCompatibilityResponse() const
    {
        ITS_REQUIRE(OptionINServiceCompatibilityResponse());
        return static_cast<const INServiceCompatibilityResponse&> (ElementAt(9));
    }

    void SetServiceInteractionIndicatorsTwo(ServiceInteractionIndicatorsTwo* element)
    {
        ITS_REQUIRE(element != NULL);
        element->AsnObject::SetDescription(GetServiceInteractionIndicatorsTwoStaticDescription());
        AddElement(10, element);
    }

    void SetServiceInteractionIndicatorsTwo(const ServiceInteractionIndicatorsTwo& element)
    {
        its::AsnObject& asnObject = const_cast<ServiceInteractionIndicatorsTwo&>(element);
        asnObject.SetDescription(GetServiceInteractionIndicatorsTwoStaticDescription());
        AddElement(10, element);
    }

    bool OptionServiceInteractionIndicatorsTwo() const
    {
        return Contains(10);
    }

    const ServiceInteractionIndicatorsTwo& GetServiceInteractionIndicatorsTwo() const
    {
        ITS_REQUIRE(OptionServiceInteractionIndicatorsTwo());
        return static_cast<const ServiceInteractionIndicatorsTwo&> (ElementAt(10));
    }

};



} // namespace.

#endif    // !defined(_INAP_CS2_INITIATE_CALL_ATTEMPT_ARG_H_)

