############################################################################
#                                                                          #
#     Copyright 2006 IntelliNet Technologies, Inc. All Rights Reserved.    #
#             Manufactured in the United States of America.                #
#       1990 W. New Haven Ste. 312, Melbourne, Florida, 32904 U.S.A.       #
#                                                                          #
#   This product and related documentation is protected by copyright and   #
#   distributed under licenses restricting its use, copying, distribution  #
#   and decompilation.  No part of this product or related documentation   #
#   may be reproduced in any form by any means without prior written       #
#   authorization of IntelliNet Technologies and its licensors, if any.    #
#                                                                          #
#   RESTRICTED RIGHTS LEGEND:  Use, duplication, or disclosure by the      #
#   government is subject to restrictions as set forth in subparagraph     #
#   (c)(1)(ii) of the Rights in Technical Data and Computer Software       #
#   clause at DFARS 252.227-7013 and FAR 52.227-19.                        #
#                                                                          #
############################################################################
#                                                                          #
# CONTRACT: INTERNAL                                                       #
############################################################################
# FILE: Makefile                                                            
# LOG: $Log: Makefile,v $
# LOG: Revision 1.1.2.1  2015/05/18 05:15:10  kpnithin
# LOG: cxdx v12 Test tool developed with new protocol file
# LOG:
# LOG: Revision 1.1.6.2  2014/02/12 08:06:13  millayaraja
# LOG:  added testapp s6a_r10 for IWF
# LOG:
# LOG: Revision 1.1.2.2  2013/02/14 05:27:34  brajappa
# LOG: Not building distributed mode app
# LOG:
# LOG: Revision 1.1.2.1  2012/12/26 19:09:01  brajappa
# LOG: Makefiles checked for s6a release 10 test app
# LOG:
# LOG: Revision 1.1.2.1  2012/07/09 08:53:44  pramana
# LOG: New test code added for S6a, S13 for Release 10 support (Bug 48).
# LOG:
# LOG: Revision 1.1  2008/08/19 06:58:33  sureshj
# LOG: Baseline demo application for s6a interface.
# LOG:								   
# ID: $Id: Makefile,v 1.1.2.1 2015/05/18 05:15:10 kpnithin Exp $							   
############################################################################
#
# components under this project
#
.PHONY: all clean realclean test

all :
	make -f Makefile.stat ; 
	##make -f Makefile.dist ; \

clean:
	make clean -f Makefile.stat ; \
	##make clean -f Makefile.dist ; \

