//
// Generated by IntelliAsnCC ASN.1 compiler (C, C++, Java).
//
// Do not edit!
//
//
//
// (C) 2000, 2001 IntelliNet Technologies Inc. All Rights Reserved.
//
//


#include <inap_cs2_name_resolution_phase.h>

#include <AsnDescEnumerated.h>


using namespace its;
using namespace inap_cs2;



AsnDescObject* NameResolutionPhase::GetStaticDescription()
{
    static volatile bool initialized = false;
    static AsnDescObject* result = NULL;
    static AsnDescEnumerated staticDesc;

    if (initialized)
    {
        return result;
    }

    Asn::Lock();

    if (initialized)
    {
        Asn::Unlock();
        return result;
    }
    else
    {
        if (CheckLicense(ITS_LIC_CAP_INAP) != ITS_TRUE)
        {
            Asn::Unlock();
            exit(0);
        }

        staticDesc.SetCloneForFactory(new NameResolutionPhase(&staticDesc));
        staticDesc.TagAddLevel(new Tag(Tag::ASN_CLASS_UNIVERSAL, Tag::ASN_PRIMITIVE, 10));
        staticDesc._valueSet.insert(1);
        staticDesc._valueSet.insert(2);
        staticDesc._valueSet.insert(3);
        static AsnDescEnumerated::NamedNumber namedNumberList[] = {{"notStarted", 1}, {"proceeding", 2}, {"completed", 3}, {NULL, 0}};
        staticDesc.SetNamedNumberList(namedNumberList);
        static AsnDescEnumerated::NamedNumber namedNumberExtList[] = {{NULL, 0}};
        staticDesc.SetNamedNumberExtList(namedNumberExtList);
        staticDesc.SetTypeName("NameResolutionPhase");
        result = &staticDesc;
        initialized = true;
        Asn::Unlock();
        return result;
    }
}

long NameResolutionPhase::Get(const std::string& valueName) const
{
    if (valueName == "notStarted")
    {
        return 1;
    }
    else if (valueName == "proceeding")
    {
        return 2;
    }
    else if (valueName == "completed")
    {
        return 3;
    }
    else
    {
        bool invalid_value_name = false;
        ITS_ASSERT(invalid_value_name);

        return 0;
    }
}

std::string NameResolutionPhase::Get(long value) const
{
    if (value == 1)
    {
        return "notStarted";
    }
    else if (value == 2)
    {
        return "proceeding";
    }
    else if (value == 3)
    {
        return "completed";
    }
    else
    {
        bool invalid_value = false;
        ITS_ASSERT(invalid_value);

        return "";
    }
}

std::string NameResolutionPhase::GetExt(long value) const
{
    return "";
}





